[addresses]
emoji = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
emoji = "0xc0de"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "Move Emojis"
upgrade_policy = "immutable"
version = "1.0.0"
