[addresses]
black_heart_market = "0x586c4b2f4c0f86b08327b1a135ddcb778a75e9c01a60d1a70278dd09c3bbbeae"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "BlackHeartCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
