[addresses]
yellow_heart_market_address = "0x6ba9e8b95825fffbfcc3fc743ec7461c13f334f8b3d5c0a30988b6d4399a003a"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "TestCoinFactory"
upgrade_policy = "compatible"
version = "1.0.0"
