# check-workflow: exempt
description: 'Build a Vercel preview of the project'
name: 'Vercel preview'
runs:
  steps:
  - uses: pnpm/action-setup@v4
    with:
      version: '9.4.0'
      run_install: false
  - uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: 'pnpm'
  using: 'composite'
...
