---
name: |
  Run the TypeScript linter
runs:
  steps:
  - uses: 'actions/setup-node@v4'
    with:
      node-version-file: '${{ env.TS_DIR }}/.node-version'
      registry-url: 'https://registry.npmjs.org'
  - uses: 'pnpm/action-setup@v4'
    with:
      package_json_file: '${{ env.TS_DIR }}/package.json'
  - run: |
      cd ${{ env.TS_DIR }} &&
      pnpm install --frozen-lockfile && pnpm lint
    shell: 'bash'
  using: 'composite'
...
