# cspell:word TMPDIR
---
name: |
  Run the TypeScript linter
runs:
  steps:
  - uses: 'actions/setup-node@v3'
    with:
      node-version-file: '$TS_API_DIR/.node-version'
      registry-url: 'https://registry.npmjs.org'
  - uses: 'pnpm/action-setup@v2'
    with:
      version: '8.9.0'
  - run: |
      cd $TS_API_DIR && pnpm install --frozen-lockfile && pnpm lint
    shell: 'bash'
  using: 'composite'
...
