env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      run: pnpm install --global vercel@latest
on:
  pull_request:
    ignore:
    - 'fallback'
    - 'production'
