// cspell:disable

export const CHAT_EMOJIS = {
  "🧑‍🎨": "artist",
  "🧑🏿‍🎨": "artist: dark skin tone",
  "🧑🏻‍🎨": "artist: light skin tone",
  "🧑🏽‍🎨": "artist: medium skin tone",
  "🧑🏾‍🎨": "artist: medium-dark skin tone",
  "🧑🏼‍🎨": "artist: medium-light skin tone",
  "🧑‍🚀": "astronaut",
  "🧑🏿‍🚀": "astronaut: dark skin tone",
  "🧑🏻‍🚀": "astronaut: light skin tone",
  "🧑🏽‍🚀": "astronaut: medium skin tone",
  "🧑🏾‍🚀": "astronaut: medium-dark skin tone",
  "🧑🏼‍🚀": "astronaut: medium-light skin tone",
  "⛓️‍💥": "broken chain",
  "🍄‍🟫": "brown mushroom",
  "🧑‍🍳": "cook",
  "🧑🏿‍🍳": "cook: dark skin tone",
  "🧑🏻‍🍳": "cook: light skin tone",
  "🧑🏽‍🍳": "cook: medium skin tone",
  "🧑🏾‍🍳": "cook: medium-dark skin tone",
  "🧑🏼‍🍳": "cook: medium-light skin tone",
  "👨‍❤️‍👨": "couple with heart: man, man",
  "👩‍❤️‍👨": "couple with heart: woman, man",
  "👩‍❤️‍👩": "couple with heart: woman, woman",
  "🧏‍♂️": "deaf man",
  "🧏🏿‍♂️": "deaf man: dark skin tone",
  "🧏🏻‍♂️": "deaf man: light skin tone",
  "🧏🏽‍♂️": "deaf man: medium skin tone",
  "🧏🏾‍♂️": "deaf man: medium-dark skin tone",
  "🧏🏼‍♂️": "deaf man: medium-light skin tone",
  "🧏‍♀️": "deaf woman",
  "🧏🏿‍♀️": "deaf woman: dark skin tone",
  "🧏🏻‍♀️": "deaf woman: light skin tone",
  "🧏🏽‍♀️": "deaf woman: medium skin tone",
  "🧏🏾‍♀️": "deaf woman: medium-dark skin tone",
  "🧏🏼‍♀️": "deaf woman: medium-light skin tone",
  "👁️‍🗨️": "eye in speech bubble",
  "😮‍💨": "face exhaling",
  "😶‍🌫️": "face in clouds",
  "😵‍💫": "face with spiral eyes",
  "🧑‍🏭": "factory worker",
  "🧑🏿‍🏭": "factory worker: dark skin tone",
  "🧑🏻‍🏭": "factory worker: light skin tone",
  "🧑🏽‍🏭": "factory worker: medium skin tone",
  "🧑🏾‍🏭": "factory worker: medium-dark skin tone",
  "🧑🏼‍🏭": "factory worker: medium-light skin tone",
  "🧑‍🧑‍🧒": "family: adult, adult, child",
  "🧑‍🧑‍🧒‍🧒": "family: adult, adult, child, child",
  "🧑‍🧒": "family: adult, child",
  "🧑‍🧒‍🧒": "family: adult, child, child",
  "👨‍👦": "family: man, boy",
  "👨‍👦‍👦": "family: man, boy, boy",
  "👨‍👧": "family: man, girl",
  "👨‍👧‍👦": "family: man, girl, boy",
  "👨‍👧‍👧": "family: man, girl, girl",
  "👨‍👨‍👦": "family: man, man, boy",
  "👨‍👨‍👦‍👦": "family: man, man, boy, boy",
  "👨‍👨‍👧": "family: man, man, girl",
  "👨‍👨‍👧‍👦": "family: man, man, girl, boy",
  "👨‍👨‍👧‍👧": "family: man, man, girl, girl",
  "👨‍👩‍👦": "family: man, woman, boy",
  "👨‍👩‍👦‍👦": "family: man, woman, boy, boy",
  "👨‍👩‍👧": "family: man, woman, girl",
  "👨‍👩‍👧‍👦": "family: man, woman, girl, boy",
  "👨‍👩‍👧‍👧": "family: man, woman, girl, girl",
  "👩‍👦": "family: woman, boy",
  "👩‍👦‍👦": "family: woman, boy, boy",
  "👩‍👧": "family: woman, girl",
  "👩‍👧‍👦": "family: woman, girl, boy",
  "👩‍👧‍👧": "family: woman, girl, girl",
  "👩‍👩‍👦": "family: woman, woman, boy",
  "👩‍👩‍👦‍👦": "family: woman, woman, boy, boy",
  "👩‍👩‍👧": "family: woman, woman, girl",
  "👩‍👩‍👧‍👦": "family: woman, woman, girl, boy",
  "👩‍👩‍👧‍👧": "family: woman, woman, girl, girl",
  "🧑‍🌾": "farmer",
  "🧑🏿‍🌾": "farmer: dark skin tone",
  "🧑🏻‍🌾": "farmer: light skin tone",
  "🧑🏽‍🌾": "farmer: medium skin tone",
  "🧑🏾‍🌾": "farmer: medium-dark skin tone",
  "🧑🏼‍🌾": "farmer: medium-light skin tone",
  "🧑‍🚒": "firefighter",
  "🧑🏿‍🚒": "firefighter: dark skin tone",
  "🧑🏻‍🚒": "firefighter: light skin tone",
  "🧑🏽‍🚒": "firefighter: medium skin tone",
  "🧑🏾‍🚒": "firefighter: medium-dark skin tone",
  "🧑🏼‍🚒": "firefighter: medium-light skin tone",
  "🏴󠁧󠁢󠁥󠁮󠁧󠁿": "flag: England",
  "🏴󠁧󠁢󠁳󠁣󠁴󠁿": "flag: Scotland",
  "🏴󠁧󠁢󠁷󠁬󠁳󠁿": "flag: Wales",
  "🫱🏿‍🫲🏻": "handshake: dark skin tone, light skin tone",
  "🫱🏿‍🫲🏽": "handshake: dark skin tone, medium skin tone",
  "🫱🏿‍🫲🏾": "handshake: dark skin tone, medium-dark skin tone",
  "🫱🏿‍🫲🏼": "handshake: dark skin tone, medium-light skin tone",
  "🫱🏻‍🫲🏿": "handshake: light skin tone, dark skin tone",
  "🫱🏻‍🫲🏽": "handshake: light skin tone, medium skin tone",
  "🫱🏻‍🫲🏾": "handshake: light skin tone, medium-dark skin tone",
  "🫱🏻‍🫲🏼": "handshake: light skin tone, medium-light skin tone",
  "🫱🏽‍🫲🏿": "handshake: medium skin tone, dark skin tone",
  "🫱🏽‍🫲🏻": "handshake: medium skin tone, light skin tone",
  "🫱🏽‍🫲🏾": "handshake: medium skin tone, medium-dark skin tone",
  "🫱🏽‍🫲🏼": "handshake: medium skin tone, medium-light skin tone",
  "🫱🏾‍🫲🏿": "handshake: medium-dark skin tone, dark skin tone",
  "🫱🏾‍🫲🏻": "handshake: medium-dark skin tone, light skin tone",
  "🫱🏾‍🫲🏽": "handshake: medium-dark skin tone, medium skin tone",
  "🫱🏾‍🫲🏼": "handshake: medium-dark skin tone, medium-light skin tone",
  "🫱🏼‍🫲🏿": "handshake: medium-light skin tone, dark skin tone",
  "🫱🏼‍🫲🏻": "handshake: medium-light skin tone, light skin tone",
  "🫱🏼‍🫲🏽": "handshake: medium-light skin tone, medium skin tone",
  "🫱🏼‍🫲🏾": "handshake: medium-light skin tone, medium-dark skin tone",
  "🙂‍↔️": "head shaking horizontally",
  "🙂‍↕️": "head shaking vertically",
  "🧑‍⚕️": "health worker",
  "🧑🏿‍⚕️": "health worker: dark skin tone",
  "🧑🏻‍⚕️": "health worker: light skin tone",
  "🧑🏽‍⚕️": "health worker: medium skin tone",
  "🧑🏾‍⚕️": "health worker: medium-dark skin tone",
  "🧑🏼‍⚕️": "health worker: medium-light skin tone",
  "❤️‍🔥": "heart on fire",
  "🧑‍⚖️": "judge",
  "🧑🏿‍⚖️": "judge: dark skin tone",
  "🧑🏻‍⚖️": "judge: light skin tone",
  "🧑🏽‍⚖️": "judge: medium skin tone",
  "🧑🏾‍⚖️": "judge: medium-dark skin tone",
  "🧑🏼‍⚖️": "judge: medium-light skin tone",
  "🍋‍🟩": "lime",
  "👨‍🎨": "man artist",
  "👨🏿‍🎨": "man artist: dark skin tone",
  "👨🏻‍🎨": "man artist: light skin tone",
  "👨🏽‍🎨": "man artist: medium skin tone",
  "👨🏾‍🎨": "man artist: medium-dark skin tone",
  "👨🏼‍🎨": "man artist: medium-light skin tone",
  "👨‍🚀": "man astronaut",
  "👨🏿‍🚀": "man astronaut: dark skin tone",
  "👨🏻‍🚀": "man astronaut: light skin tone",
  "👨🏽‍🚀": "man astronaut: medium skin tone",
  "👨🏾‍🚀": "man astronaut: medium-dark skin tone",
  "👨🏼‍🚀": "man astronaut: medium-light skin tone",
  "🚴‍♂️": "man biking",
  "🚴🏿‍♂️": "man biking: dark skin tone",
  "🚴🏻‍♂️": "man biking: light skin tone",
  "🚴🏽‍♂️": "man biking: medium skin tone",
  "🚴🏾‍♂️": "man biking: medium-dark skin tone",
  "🚴🏼‍♂️": "man biking: medium-light skin tone",
  "⛹️‍♂️": "man bouncing ball",
  "⛹🏿‍♂️": "man bouncing ball: dark skin tone",
  "⛹🏻‍♂️": "man bouncing ball: light skin tone",
  "⛹🏽‍♂️": "man bouncing ball: medium skin tone",
  "⛹🏾‍♂️": "man bouncing ball: medium-dark skin tone",
  "⛹🏼‍♂️": "man bouncing ball: medium-light skin tone",
  "🙇‍♂️": "man bowing",
  "🙇🏿‍♂️": "man bowing: dark skin tone",
  "🙇🏻‍♂️": "man bowing: light skin tone",
  "🙇🏽‍♂️": "man bowing: medium skin tone",
  "🙇🏾‍♂️": "man bowing: medium-dark skin tone",
  "🙇🏼‍♂️": "man bowing: medium-light skin tone",
  "🤸‍♂️": "man cartwheeling",
  "🤸🏿‍♂️": "man cartwheeling: dark skin tone",
  "🤸🏻‍♂️": "man cartwheeling: light skin tone",
  "🤸🏽‍♂️": "man cartwheeling: medium skin tone",
  "🤸🏾‍♂️": "man cartwheeling: medium-dark skin tone",
  "🤸🏼‍♂️": "man cartwheeling: medium-light skin tone",
  "🧗‍♂️": "man climbing",
  "🧗🏿‍♂️": "man climbing: dark skin tone",
  "🧗🏻‍♂️": "man climbing: light skin tone",
  "🧗🏽‍♂️": "man climbing: medium skin tone",
  "🧗🏾‍♂️": "man climbing: medium-dark skin tone",
  "🧗🏼‍♂️": "man climbing: medium-light skin tone",
  "👷‍♂️": "man construction worker",
  "👷🏿‍♂️": "man construction worker: dark skin tone",
  "👷🏻‍♂️": "man construction worker: light skin tone",
  "👷🏽‍♂️": "man construction worker: medium skin tone",
  "👷🏾‍♂️": "man construction worker: medium-dark skin tone",
  "👷🏼‍♂️": "man construction worker: medium-light skin tone",
  "👨‍🍳": "man cook",
  "👨🏿‍🍳": "man cook: dark skin tone",
  "👨🏻‍🍳": "man cook: light skin tone",
  "👨🏽‍🍳": "man cook: medium skin tone",
  "👨🏾‍🍳": "man cook: medium-dark skin tone",
  "👨🏼‍🍳": "man cook: medium-light skin tone",
  "🕵️‍♂️": "man detective",
  "🕵🏿‍♂️": "man detective: dark skin tone",
  "🕵🏻‍♂️": "man detective: light skin tone",
  "🕵🏽‍♂️": "man detective: medium skin tone",
  "🕵🏾‍♂️": "man detective: medium-dark skin tone",
  "🕵🏼‍♂️": "man detective: medium-light skin tone",
  "🧝‍♂️": "man elf",
  "🧝🏿‍♂️": "man elf: dark skin tone",
  "🧝🏻‍♂️": "man elf: light skin tone",
  "🧝🏽‍♂️": "man elf: medium skin tone",
  "🧝🏾‍♂️": "man elf: medium-dark skin tone",
  "🧝🏼‍♂️": "man elf: medium-light skin tone",
  "🤦‍♂️": "man facepalming",
  "🤦🏿‍♂️": "man facepalming: dark skin tone",
  "🤦🏻‍♂️": "man facepalming: light skin tone",
  "🤦🏽‍♂️": "man facepalming: medium skin tone",
  "🤦🏾‍♂️": "man facepalming: medium-dark skin tone",
  "🤦🏼‍♂️": "man facepalming: medium-light skin tone",
  "👨‍🏭": "man factory worker",
  "👨🏿‍🏭": "man factory worker: dark skin tone",
  "👨🏻‍🏭": "man factory worker: light skin tone",
  "👨🏽‍🏭": "man factory worker: medium skin tone",
  "👨🏾‍🏭": "man factory worker: medium-dark skin tone",
  "👨🏼‍🏭": "man factory worker: medium-light skin tone",
  "🧚‍♂️": "man fairy",
  "🧚🏿‍♂️": "man fairy: dark skin tone",
  "🧚🏻‍♂️": "man fairy: light skin tone",
  "🧚🏽‍♂️": "man fairy: medium skin tone",
  "🧚🏾‍♂️": "man fairy: medium-dark skin tone",
  "🧚🏼‍♂️": "man fairy: medium-light skin tone",
  "👨‍🌾": "man farmer",
  "👨🏿‍🌾": "man farmer: dark skin tone",
  "👨🏻‍🌾": "man farmer: light skin tone",
  "👨🏽‍🌾": "man farmer: medium skin tone",
  "👨🏾‍🌾": "man farmer: medium-dark skin tone",
  "👨🏼‍🌾": "man farmer: medium-light skin tone",
  "👨‍🍼": "man feeding baby",
  "👨🏿‍🍼": "man feeding baby: dark skin tone",
  "👨🏻‍🍼": "man feeding baby: light skin tone",
  "👨🏽‍🍼": "man feeding baby: medium skin tone",
  "👨🏾‍🍼": "man feeding baby: medium-dark skin tone",
  "👨🏼‍🍼": "man feeding baby: medium-light skin tone",
  "👨‍🚒": "man firefighter",
  "👨🏿‍🚒": "man firefighter: dark skin tone",
  "👨🏻‍🚒": "man firefighter: light skin tone",
  "👨🏽‍🚒": "man firefighter: medium skin tone",
  "👨🏾‍🚒": "man firefighter: medium-dark skin tone",
  "👨🏼‍🚒": "man firefighter: medium-light skin tone",
  "🙍‍♂️": "man frowning",
  "🙍🏿‍♂️": "man frowning: dark skin tone",
  "🙍🏻‍♂️": "man frowning: light skin tone",
  "🙍🏽‍♂️": "man frowning: medium skin tone",
  "🙍🏾‍♂️": "man frowning: medium-dark skin tone",
  "🙍🏼‍♂️": "man frowning: medium-light skin tone",
  "🧞‍♂️": "man genie",
  "🙅‍♂️": "man gesturing NO",
  "🙅🏿‍♂️": "man gesturing NO: dark skin tone",
  "🙅🏻‍♂️": "man gesturing NO: light skin tone",
  "🙅🏽‍♂️": "man gesturing NO: medium skin tone",
  "🙅🏾‍♂️": "man gesturing NO: medium-dark skin tone",
  "🙅🏼‍♂️": "man gesturing NO: medium-light skin tone",
  "🙆‍♂️": "man gesturing OK",
  "🙆🏿‍♂️": "man gesturing OK: dark skin tone",
  "🙆🏻‍♂️": "man gesturing OK: light skin tone",
  "🙆🏽‍♂️": "man gesturing OK: medium skin tone",
  "🙆🏾‍♂️": "man gesturing OK: medium-dark skin tone",
  "🙆🏼‍♂️": "man gesturing OK: medium-light skin tone",
  "💇‍♂️": "man getting haircut",
  "💇🏿‍♂️": "man getting haircut: dark skin tone",
  "💇🏻‍♂️": "man getting haircut: light skin tone",
  "💇🏽‍♂️": "man getting haircut: medium skin tone",
  "💇🏾‍♂️": "man getting haircut: medium-dark skin tone",
  "💇🏼‍♂️": "man getting haircut: medium-light skin tone",
  "💆‍♂️": "man getting massage",
  "💆🏿‍♂️": "man getting massage: dark skin tone",
  "💆🏻‍♂️": "man getting massage: light skin tone",
  "💆🏽‍♂️": "man getting massage: medium skin tone",
  "💆🏾‍♂️": "man getting massage: medium-dark skin tone",
  "💆🏼‍♂️": "man getting massage: medium-light skin tone",
  "🏌️‍♂️": "man golfing",
  "🏌🏿‍♂️": "man golfing: dark skin tone",
  "🏌🏻‍♂️": "man golfing: light skin tone",
  "🏌🏽‍♂️": "man golfing: medium skin tone",
  "🏌🏾‍♂️": "man golfing: medium-dark skin tone",
  "🏌🏼‍♂️": "man golfing: medium-light skin tone",
  "💂‍♂️": "man guard",
  "💂🏿‍♂️": "man guard: dark skin tone",
  "💂🏻‍♂️": "man guard: light skin tone",
  "💂🏽‍♂️": "man guard: medium skin tone",
  "💂🏾‍♂️": "man guard: medium-dark skin tone",
  "💂🏼‍♂️": "man guard: medium-light skin tone",
  "👨‍⚕️": "man health worker",
  "👨🏿‍⚕️": "man health worker: dark skin tone",
  "👨🏻‍⚕️": "man health worker: light skin tone",
  "👨🏽‍⚕️": "man health worker: medium skin tone",
  "👨🏾‍⚕️": "man health worker: medium-dark skin tone",
  "👨🏼‍⚕️": "man health worker: medium-light skin tone",
  "🧘‍♂️": "man in lotus position",
  "🧘🏿‍♂️": "man in lotus position: dark skin tone",
  "🧘🏻‍♂️": "man in lotus position: light skin tone",
  "🧘🏽‍♂️": "man in lotus position: medium skin tone",
  "🧘🏾‍♂️": "man in lotus position: medium-dark skin tone",
  "🧘🏼‍♂️": "man in lotus position: medium-light skin tone",
  "👨‍🦽": "man in manual wheelchair",
  "👨‍🦽‍➡️": "man in manual wheelchair facing right",
  "👨🏿‍🦽‍➡️": "man in manual wheelchair facing right: dark skin tone",
  "👨🏻‍🦽‍➡️": "man in manual wheelchair facing right: light skin tone",
  "👨🏽‍🦽‍➡️": "man in manual wheelchair facing right: medium skin tone",
  "👨🏾‍🦽‍➡️": "man in manual wheelchair facing right: medium-dark skin tone",
  "👨🏼‍🦽‍➡️": "man in manual wheelchair facing right: medium-light skin tone",
  "👨🏿‍🦽": "man in manual wheelchair: dark skin tone",
  "👨🏻‍🦽": "man in manual wheelchair: light skin tone",
  "👨🏽‍🦽": "man in manual wheelchair: medium skin tone",
  "👨🏾‍🦽": "man in manual wheelchair: medium-dark skin tone",
  "👨🏼‍🦽": "man in manual wheelchair: medium-light skin tone",
  "👨‍🦼": "man in motorized wheelchair",
  "👨‍🦼‍➡️": "man in motorized wheelchair facing right",
  "👨🏿‍🦼‍➡️": "man in motorized wheelchair facing right: dark skin tone",
  "👨🏻‍🦼‍➡️": "man in motorized wheelchair facing right: light skin tone",
  "👨🏽‍🦼‍➡️": "man in motorized wheelchair facing right: medium skin tone",
  "👨🏾‍🦼‍➡️": "man in motorized wheelchair facing right: medium-dark skin tone",
  "👨🏼‍🦼‍➡️": "man in motorized wheelchair facing right: medium-light skin tone",
  "👨🏿‍🦼": "man in motorized wheelchair: dark skin tone",
  "👨🏻‍🦼": "man in motorized wheelchair: light skin tone",
  "👨🏽‍🦼": "man in motorized wheelchair: medium skin tone",
  "👨🏾‍🦼": "man in motorized wheelchair: medium-dark skin tone",
  "👨🏼‍🦼": "man in motorized wheelchair: medium-light skin tone",
  "🧖‍♂️": "man in steamy room",
  "🧖🏿‍♂️": "man in steamy room: dark skin tone",
  "🧖🏻‍♂️": "man in steamy room: light skin tone",
  "🧖🏽‍♂️": "man in steamy room: medium skin tone",
  "🧖🏾‍♂️": "man in steamy room: medium-dark skin tone",
  "🧖🏼‍♂️": "man in steamy room: medium-light skin tone",
  "🤵‍♂️": "man in tuxedo",
  "🤵🏿‍♂️": "man in tuxedo: dark skin tone",
  "🤵🏻‍♂️": "man in tuxedo: light skin tone",
  "🤵🏽‍♂️": "man in tuxedo: medium skin tone",
  "🤵🏾‍♂️": "man in tuxedo: medium-dark skin tone",
  "🤵🏼‍♂️": "man in tuxedo: medium-light skin tone",
  "👨‍⚖️": "man judge",
  "👨🏿‍⚖️": "man judge: dark skin tone",
  "👨🏻‍⚖️": "man judge: light skin tone",
  "👨🏽‍⚖️": "man judge: medium skin tone",
  "👨🏾‍⚖️": "man judge: medium-dark skin tone",
  "👨🏼‍⚖️": "man judge: medium-light skin tone",
  "🤹‍♂️": "man juggling",
  "🤹🏿‍♂️": "man juggling: dark skin tone",
  "🤹🏻‍♂️": "man juggling: light skin tone",
  "🤹🏽‍♂️": "man juggling: medium skin tone",
  "🤹🏾‍♂️": "man juggling: medium-dark skin tone",
  "🤹🏼‍♂️": "man juggling: medium-light skin tone",
  "🧎‍♂️": "man kneeling",
  "🧎‍♂️‍➡️": "man kneeling facing right",
  "🧎🏿‍♂️‍➡️": "man kneeling facing right: dark skin tone",
  "🧎🏻‍♂️‍➡️": "man kneeling facing right: light skin tone",
  "🧎🏽‍♂️‍➡️": "man kneeling facing right: medium skin tone",
  "🧎🏾‍♂️‍➡️": "man kneeling facing right: medium-dark skin tone",
  "🧎🏼‍♂️‍➡️": "man kneeling facing right: medium-light skin tone",
  "🧎🏿‍♂️": "man kneeling: dark skin tone",
  "🧎🏻‍♂️": "man kneeling: light skin tone",
  "🧎🏽‍♂️": "man kneeling: medium skin tone",
  "🧎🏾‍♂️": "man kneeling: medium-dark skin tone",
  "🧎🏼‍♂️": "man kneeling: medium-light skin tone",
  "🏋️‍♂️": "man lifting weights",
  "🏋🏿‍♂️": "man lifting weights: dark skin tone",
  "🏋🏻‍♂️": "man lifting weights: light skin tone",
  "🏋🏽‍♂️": "man lifting weights: medium skin tone",
  "🏋🏾‍♂️": "man lifting weights: medium-dark skin tone",
  "🏋🏼‍♂️": "man lifting weights: medium-light skin tone",
  "🧙‍♂️": "man mage",
  "🧙🏿‍♂️": "man mage: dark skin tone",
  "🧙🏻‍♂️": "man mage: light skin tone",
  "🧙🏽‍♂️": "man mage: medium skin tone",
  "🧙🏾‍♂️": "man mage: medium-dark skin tone",
  "🧙🏼‍♂️": "man mage: medium-light skin tone",
  "👨‍🔧": "man mechanic",
  "👨🏿‍🔧": "man mechanic: dark skin tone",
  "👨🏻‍🔧": "man mechanic: light skin tone",
  "👨🏽‍🔧": "man mechanic: medium skin tone",
  "👨🏾‍🔧": "man mechanic: medium-dark skin tone",
  "👨🏼‍🔧": "man mechanic: medium-light skin tone",
  "🚵‍♂️": "man mountain biking",
  "🚵🏿‍♂️": "man mountain biking: dark skin tone",
  "🚵🏻‍♂️": "man mountain biking: light skin tone",
  "🚵🏽‍♂️": "man mountain biking: medium skin tone",
  "🚵🏾‍♂️": "man mountain biking: medium-dark skin tone",
  "🚵🏼‍♂️": "man mountain biking: medium-light skin tone",
  "👨‍💼": "man office worker",
  "👨🏿‍💼": "man office worker: dark skin tone",
  "👨🏻‍💼": "man office worker: light skin tone",
  "👨🏽‍💼": "man office worker: medium skin tone",
  "👨🏾‍💼": "man office worker: medium-dark skin tone",
  "👨🏼‍💼": "man office worker: medium-light skin tone",
  "👨‍✈️": "man pilot",
  "👨🏿‍✈️": "man pilot: dark skin tone",
  "👨🏻‍✈️": "man pilot: light skin tone",
  "👨🏽‍✈️": "man pilot: medium skin tone",
  "👨🏾‍✈️": "man pilot: medium-dark skin tone",
  "👨🏼‍✈️": "man pilot: medium-light skin tone",
  "🤾‍♂️": "man playing handball",
  "🤾🏿‍♂️": "man playing handball: dark skin tone",
  "🤾🏻‍♂️": "man playing handball: light skin tone",
  "🤾🏽‍♂️": "man playing handball: medium skin tone",
  "🤾🏾‍♂️": "man playing handball: medium-dark skin tone",
  "🤾🏼‍♂️": "man playing handball: medium-light skin tone",
  "🤽‍♂️": "man playing water polo",
  "🤽🏿‍♂️": "man playing water polo: dark skin tone",
  "🤽🏻‍♂️": "man playing water polo: light skin tone",
  "🤽🏽‍♂️": "man playing water polo: medium skin tone",
  "🤽🏾‍♂️": "man playing water polo: medium-dark skin tone",
  "🤽🏼‍♂️": "man playing water polo: medium-light skin tone",
  "👮‍♂️": "man police officer",
  "👮🏿‍♂️": "man police officer: dark skin tone",
  "👮🏻‍♂️": "man police officer: light skin tone",
  "👮🏽‍♂️": "man police officer: medium skin tone",
  "👮🏾‍♂️": "man police officer: medium-dark skin tone",
  "👮🏼‍♂️": "man police officer: medium-light skin tone",
  "🙎‍♂️": "man pouting",
  "🙎🏿‍♂️": "man pouting: dark skin tone",
  "🙎🏻‍♂️": "man pouting: light skin tone",
  "🙎🏽‍♂️": "man pouting: medium skin tone",
  "🙎🏾‍♂️": "man pouting: medium-dark skin tone",
  "🙎🏼‍♂️": "man pouting: medium-light skin tone",
  "🙋‍♂️": "man raising hand",
  "🙋🏿‍♂️": "man raising hand: dark skin tone",
  "🙋🏻‍♂️": "man raising hand: light skin tone",
  "🙋🏽‍♂️": "man raising hand: medium skin tone",
  "🙋🏾‍♂️": "man raising hand: medium-dark skin tone",
  "🙋🏼‍♂️": "man raising hand: medium-light skin tone",
  "🚣‍♂️": "man rowing boat",
  "🚣🏿‍♂️": "man rowing boat: dark skin tone",
  "🚣🏻‍♂️": "man rowing boat: light skin tone",
  "🚣🏽‍♂️": "man rowing boat: medium skin tone",
  "🚣🏾‍♂️": "man rowing boat: medium-dark skin tone",
  "🚣🏼‍♂️": "man rowing boat: medium-light skin tone",
  "🏃‍♂️": "man running",
  "🏃‍♂️‍➡️": "man running facing right",
  "🏃🏿‍♂️‍➡️": "man running facing right: dark skin tone",
  "🏃🏻‍♂️‍➡️": "man running facing right: light skin tone",
  "🏃🏽‍♂️‍➡️": "man running facing right: medium skin tone",
  "🏃🏾‍♂️‍➡️": "man running facing right: medium-dark skin tone",
  "🏃🏼‍♂️‍➡️": "man running facing right: medium-light skin tone",
  "🏃🏿‍♂️": "man running: dark skin tone",
  "🏃🏻‍♂️": "man running: light skin tone",
  "🏃🏽‍♂️": "man running: medium skin tone",
  "🏃🏾‍♂️": "man running: medium-dark skin tone",
  "🏃🏼‍♂️": "man running: medium-light skin tone",
  "👨‍🔬": "man scientist",
  "👨🏿‍🔬": "man scientist: dark skin tone",
  "👨🏻‍🔬": "man scientist: light skin tone",
  "👨🏽‍🔬": "man scientist: medium skin tone",
  "👨🏾‍🔬": "man scientist: medium-dark skin tone",
  "👨🏼‍🔬": "man scientist: medium-light skin tone",
  "🤷‍♂️": "man shrugging",
  "🤷🏿‍♂️": "man shrugging: dark skin tone",
  "🤷🏻‍♂️": "man shrugging: light skin tone",
  "🤷🏽‍♂️": "man shrugging: medium skin tone",
  "🤷🏾‍♂️": "man shrugging: medium-dark skin tone",
  "🤷🏼‍♂️": "man shrugging: medium-light skin tone",
  "👨‍🎤": "man singer",
  "👨🏿‍🎤": "man singer: dark skin tone",
  "👨🏻‍🎤": "man singer: light skin tone",
  "👨🏽‍🎤": "man singer: medium skin tone",
  "👨🏾‍🎤": "man singer: medium-dark skin tone",
  "👨🏼‍🎤": "man singer: medium-light skin tone",
  "🧍‍♂️": "man standing",
  "🧍🏿‍♂️": "man standing: dark skin tone",
  "🧍🏻‍♂️": "man standing: light skin tone",
  "🧍🏽‍♂️": "man standing: medium skin tone",
  "🧍🏾‍♂️": "man standing: medium-dark skin tone",
  "🧍🏼‍♂️": "man standing: medium-light skin tone",
  "👨‍🎓": "man student",
  "👨🏿‍🎓": "man student: dark skin tone",
  "👨🏻‍🎓": "man student: light skin tone",
  "👨🏽‍🎓": "man student: medium skin tone",
  "👨🏾‍🎓": "man student: medium-dark skin tone",
  "👨🏼‍🎓": "man student: medium-light skin tone",
  "🦸‍♂️": "man superhero",
  "🦸🏿‍♂️": "man superhero: dark skin tone",
  "🦸🏻‍♂️": "man superhero: light skin tone",
  "🦸🏽‍♂️": "man superhero: medium skin tone",
  "🦸🏾‍♂️": "man superhero: medium-dark skin tone",
  "🦸🏼‍♂️": "man superhero: medium-light skin tone",
  "🦹‍♂️": "man supervillain",
  "🦹🏿‍♂️": "man supervillain: dark skin tone",
  "🦹🏻‍♂️": "man supervillain: light skin tone",
  "🦹🏽‍♂️": "man supervillain: medium skin tone",
  "🦹🏾‍♂️": "man supervillain: medium-dark skin tone",
  "🦹🏼‍♂️": "man supervillain: medium-light skin tone",
  "🏄‍♂️": "man surfing",
  "🏄🏿‍♂️": "man surfing: dark skin tone",
  "🏄🏻‍♂️": "man surfing: light skin tone",
  "🏄🏽‍♂️": "man surfing: medium skin tone",
  "🏄🏾‍♂️": "man surfing: medium-dark skin tone",
  "🏄🏼‍♂️": "man surfing: medium-light skin tone",
  "🏊‍♂️": "man swimming",
  "🏊🏿‍♂️": "man swimming: dark skin tone",
  "🏊🏻‍♂️": "man swimming: light skin tone",
  "🏊🏽‍♂️": "man swimming: medium skin tone",
  "🏊🏾‍♂️": "man swimming: medium-dark skin tone",
  "🏊🏼‍♂️": "man swimming: medium-light skin tone",
  "👨‍🏫": "man teacher",
  "👨🏿‍🏫": "man teacher: dark skin tone",
  "👨🏻‍🏫": "man teacher: light skin tone",
  "👨🏽‍🏫": "man teacher: medium skin tone",
  "👨🏾‍🏫": "man teacher: medium-dark skin tone",
  "👨🏼‍🏫": "man teacher: medium-light skin tone",
  "👨‍💻": "man technologist",
  "👨🏿‍💻": "man technologist: dark skin tone",
  "👨🏻‍💻": "man technologist: light skin tone",
  "👨🏽‍💻": "man technologist: medium skin tone",
  "👨🏾‍💻": "man technologist: medium-dark skin tone",
  "👨🏼‍💻": "man technologist: medium-light skin tone",
  "💁‍♂️": "man tipping hand",
  "💁🏿‍♂️": "man tipping hand: dark skin tone",
  "💁🏻‍♂️": "man tipping hand: light skin tone",
  "💁🏽‍♂️": "man tipping hand: medium skin tone",
  "💁🏾‍♂️": "man tipping hand: medium-dark skin tone",
  "💁🏼‍♂️": "man tipping hand: medium-light skin tone",
  "🧛‍♂️": "man vampire",
  "🧛🏿‍♂️": "man vampire: dark skin tone",
  "🧛🏻‍♂️": "man vampire: light skin tone",
  "🧛🏽‍♂️": "man vampire: medium skin tone",
  "🧛🏾‍♂️": "man vampire: medium-dark skin tone",
  "🧛🏼‍♂️": "man vampire: medium-light skin tone",
  "🚶‍♂️": "man walking",
  "🚶‍♂️‍➡️": "man walking facing right",
  "🚶🏿‍♂️‍➡️": "man walking facing right: dark skin tone",
  "🚶🏻‍♂️‍➡️": "man walking facing right: light skin tone",
  "🚶🏽‍♂️‍➡️": "man walking facing right: medium skin tone",
  "🚶🏾‍♂️‍➡️": "man walking facing right: medium-dark skin tone",
  "🚶🏼‍♂️‍➡️": "man walking facing right: medium-light skin tone",
  "🚶🏿‍♂️": "man walking: dark skin tone",
  "🚶🏻‍♂️": "man walking: light skin tone",
  "🚶🏽‍♂️": "man walking: medium skin tone",
  "🚶🏾‍♂️": "man walking: medium-dark skin tone",
  "🚶🏼‍♂️": "man walking: medium-light skin tone",
  "👳‍♂️": "man wearing turban",
  "👳🏿‍♂️": "man wearing turban: dark skin tone",
  "👳🏻‍♂️": "man wearing turban: light skin tone",
  "👳🏽‍♂️": "man wearing turban: medium skin tone",
  "👳🏾‍♂️": "man wearing turban: medium-dark skin tone",
  "👳🏼‍♂️": "man wearing turban: medium-light skin tone",
  "👰‍♂️": "man with veil",
  "👰🏿‍♂️": "man with veil: dark skin tone",
  "👰🏻‍♂️": "man with veil: light skin tone",
  "👰🏽‍♂️": "man with veil: medium skin tone",
  "👰🏾‍♂️": "man with veil: medium-dark skin tone",
  "👰🏼‍♂️": "man with veil: medium-light skin tone",
  "👨‍🦯": "man with white cane",
  "👨‍🦯‍➡️": "man with white cane facing right",
  "👨🏿‍🦯‍➡️": "man with white cane facing right: dark skin tone",
  "👨🏻‍🦯‍➡️": "man with white cane facing right: light skin tone",
  "👨🏽‍🦯‍➡️": "man with white cane facing right: medium skin tone",
  "👨🏾‍🦯‍➡️": "man with white cane facing right: medium-dark skin tone",
  "👨🏼‍🦯‍➡️": "man with white cane facing right: medium-light skin tone",
  "👨🏿‍🦯": "man with white cane: dark skin tone",
  "👨🏻‍🦯": "man with white cane: light skin tone",
  "👨🏽‍🦯": "man with white cane: medium skin tone",
  "👨🏾‍🦯": "man with white cane: medium-dark skin tone",
  "👨🏼‍🦯": "man with white cane: medium-light skin tone",
  "🧟‍♂️": "man zombie",
  "👨‍🦲": "man: bald",
  "🧔‍♂️": "man: beard",
  "👱‍♂️": "man: blond hair",
  "👨‍🦱": "man: curly hair",
  "👨🏿‍🦲": "man: dark skin tone, bald",
  "🧔🏿‍♂️": "man: dark skin tone, beard",
  "👱🏿‍♂️": "man: dark skin tone, blond hair",
  "👨🏿‍🦱": "man: dark skin tone, curly hair",
  "👨🏿‍🦰": "man: dark skin tone, red hair",
  "👨🏿‍🦳": "man: dark skin tone, white hair",
  "👨🏻‍🦲": "man: light skin tone, bald",
  "🧔🏻‍♂️": "man: light skin tone, beard",
  "👱🏻‍♂️": "man: light skin tone, blond hair",
  "👨🏻‍🦱": "man: light skin tone, curly hair",
  "👨🏻‍🦰": "man: light skin tone, red hair",
  "👨🏻‍🦳": "man: light skin tone, white hair",
  "👨🏽‍🦲": "man: medium skin tone, bald",
  "🧔🏽‍♂️": "man: medium skin tone, beard",
  "👱🏽‍♂️": "man: medium skin tone, blond hair",
  "👨🏽‍🦱": "man: medium skin tone, curly hair",
  "👨🏽‍🦰": "man: medium skin tone, red hair",
  "👨🏽‍🦳": "man: medium skin tone, white hair",
  "👨🏾‍🦲": "man: medium-dark skin tone, bald",
  "🧔🏾‍♂️": "man: medium-dark skin tone, beard",
  "👱🏾‍♂️": "man: medium-dark skin tone, blond hair",
  "👨🏾‍🦱": "man: medium-dark skin tone, curly hair",
  "👨🏾‍🦰": "man: medium-dark skin tone, red hair",
  "👨🏾‍🦳": "man: medium-dark skin tone, white hair",
  "👨🏼‍🦲": "man: medium-light skin tone, bald",
  "🧔🏼‍♂️": "man: medium-light skin tone, beard",
  "👱🏼‍♂️": "man: medium-light skin tone, blond hair",
  "👨🏼‍🦱": "man: medium-light skin tone, curly hair",
  "👨🏼‍🦰": "man: medium-light skin tone, red hair",
  "👨🏼‍🦳": "man: medium-light skin tone, white hair",
  "👨‍🦰": "man: red hair",
  "👨‍🦳": "man: white hair",
  "🧑‍🔧": "mechanic",
  "🧑🏿‍🔧": "mechanic: dark skin tone",
  "🧑🏻‍🔧": "mechanic: light skin tone",
  "🧑🏽‍🔧": "mechanic: medium skin tone",
  "🧑🏾‍🔧": "mechanic: medium-dark skin tone",
  "🧑🏼‍🔧": "mechanic: medium-light skin tone",
  "👯‍♂️": "men with bunny ears",
  "🤼‍♂️": "men wrestling",
  "❤️‍🩹": "mending heart",
  "🧜‍♀️": "mermaid",
  "🧜🏿‍♀️": "mermaid: dark skin tone",
  "🧜🏻‍♀️": "mermaid: light skin tone",
  "🧜🏽‍♀️": "mermaid: medium skin tone",
  "🧜🏾‍♀️": "mermaid: medium-dark skin tone",
  "🧜🏼‍♀️": "mermaid: medium-light skin tone",
  "🧜‍♂️": "merman",
  "🧜🏿‍♂️": "merman: dark skin tone",
  "🧜🏻‍♂️": "merman: light skin tone",
  "🧜🏽‍♂️": "merman: medium skin tone",
  "🧜🏾‍♂️": "merman: medium-dark skin tone",
  "🧜🏼‍♂️": "merman: medium-light skin tone",
  "🧑‍🎄": "mx claus",
  "🧑🏿‍🎄": "mx claus: dark skin tone",
  "🧑🏻‍🎄": "mx claus: light skin tone",
  "🧑🏽‍🎄": "mx claus: medium skin tone",
  "🧑🏾‍🎄": "mx claus: medium-dark skin tone",
  "🧑🏼‍🎄": "mx claus: medium-light skin tone",
  "🧑‍💼": "office worker",
  "🧑🏿‍💼": "office worker: dark skin tone",
  "🧑🏻‍💼": "office worker: light skin tone",
  "🧑🏽‍💼": "office worker: medium skin tone",
  "🧑🏾‍💼": "office worker: medium-dark skin tone",
  "🧑🏼‍💼": "office worker: medium-light skin tone",
  "🧑‍🤝‍🧑": "people holding hands",
  "🧑‍🍼": "person feeding baby",
  "🧑🏿‍🍼": "person feeding baby: dark skin tone",
  "🧑🏻‍🍼": "person feeding baby: light skin tone",
  "🧑🏽‍🍼": "person feeding baby: medium skin tone",
  "🧑🏾‍🍼": "person feeding baby: medium-dark skin tone",
  "🧑🏼‍🍼": "person feeding baby: medium-light skin tone",
  "🧑‍🦽": "person in manual wheelchair",
  "🧑‍🦽‍➡️": "person in manual wheelchair facing right",
  "🧑🏿‍🦽‍➡️": "person in manual wheelchair facing right: dark skin tone",
  "🧑🏻‍🦽‍➡️": "person in manual wheelchair facing right: light skin tone",
  "🧑🏽‍🦽‍➡️": "person in manual wheelchair facing right: medium skin tone",
  "🧑🏾‍🦽‍➡️": "person in manual wheelchair facing right: medium-dark skin tone",
  "🧑🏼‍🦽‍➡️": "person in manual wheelchair facing right: medium-light skin tone",
  "🧑🏿‍🦽": "person in manual wheelchair: dark skin tone",
  "🧑🏻‍🦽": "person in manual wheelchair: light skin tone",
  "🧑🏽‍🦽": "person in manual wheelchair: medium skin tone",
  "🧑🏾‍🦽": "person in manual wheelchair: medium-dark skin tone",
  "🧑🏼‍🦽": "person in manual wheelchair: medium-light skin tone",
  "🧑‍🦼": "person in motorized wheelchair",
  "🧑‍🦼‍➡️": "person in motorized wheelchair facing right",
  "🧑🏿‍🦼‍➡️": "person in motorized wheelchair facing right: dark skin tone",
  "🧑🏻‍🦼‍➡️": "person in motorized wheelchair facing right: light skin tone",
  "🧑🏽‍🦼‍➡️": "person in motorized wheelchair facing right: medium skin tone",
  "🧑🏾‍🦼‍➡️": "person in motorized wheelchair facing right: medium-dark skin tone",
  "🧑🏼‍🦼‍➡️": "person in motorized wheelchair facing right: medium-light skin tone",
  "🧑🏿‍🦼": "person in motorized wheelchair: dark skin tone",
  "🧑🏻‍🦼": "person in motorized wheelchair: light skin tone",
  "🧑🏽‍🦼": "person in motorized wheelchair: medium skin tone",
  "🧑🏾‍🦼": "person in motorized wheelchair: medium-dark skin tone",
  "🧑🏼‍🦼": "person in motorized wheelchair: medium-light skin tone",
  "🧎‍➡️": "person kneeling facing right",
  "🧎🏿‍➡️": "person kneeling facing right: dark skin tone",
  "🧎🏻‍➡️": "person kneeling facing right: light skin tone",
  "🧎🏽‍➡️": "person kneeling facing right: medium skin tone",
  "🧎🏾‍➡️": "person kneeling facing right: medium-dark skin tone",
  "🧎🏼‍➡️": "person kneeling facing right: medium-light skin tone",
  "🏃‍➡️": "person running facing right",
  "🏃🏿‍➡️": "person running facing right: dark skin tone",
  "🏃🏻‍➡️": "person running facing right: light skin tone",
  "🏃🏽‍➡️": "person running facing right: medium skin tone",
  "🏃🏾‍➡️": "person running facing right: medium-dark skin tone",
  "🏃🏼‍➡️": "person running facing right: medium-light skin tone",
  "🚶‍➡️": "person walking facing right",
  "🚶🏿‍➡️": "person walking facing right: dark skin tone",
  "🚶🏻‍➡️": "person walking facing right: light skin tone",
  "🚶🏽‍➡️": "person walking facing right: medium skin tone",
  "🚶🏾‍➡️": "person walking facing right: medium-dark skin tone",
  "🚶🏼‍➡️": "person walking facing right: medium-light skin tone",
  "🧑‍🦯": "person with white cane",
  "🧑‍🦯‍➡️": "person with white cane facing right",
  "🧑🏿‍🦯‍➡️": "person with white cane facing right: dark skin tone",
  "🧑🏻‍🦯‍➡️": "person with white cane facing right: light skin tone",
  "🧑🏽‍🦯‍➡️": "person with white cane facing right: medium skin tone",
  "🧑🏾‍🦯‍➡️": "person with white cane facing right: medium-dark skin tone",
  "🧑🏼‍🦯‍➡️": "person with white cane facing right: medium-light skin tone",
  "🧑🏿‍🦯": "person with white cane: dark skin tone",
  "🧑🏻‍🦯": "person with white cane: light skin tone",
  "🧑🏽‍🦯": "person with white cane: medium skin tone",
  "🧑🏾‍🦯": "person with white cane: medium-dark skin tone",
  "🧑🏼‍🦯": "person with white cane: medium-light skin tone",
  "🧑‍🦲": "person: bald",
  "🧑‍🦱": "person: curly hair",
  "🧑🏿‍🦲": "person: dark skin tone, bald",
  "🧑🏿‍🦱": "person: dark skin tone, curly hair",
  "🧑🏿‍🦰": "person: dark skin tone, red hair",
  "🧑🏿‍🦳": "person: dark skin tone, white hair",
  "🧑🏻‍🦲": "person: light skin tone, bald",
  "🧑🏻‍🦱": "person: light skin tone, curly hair",
  "🧑🏻‍🦰": "person: light skin tone, red hair",
  "🧑🏻‍🦳": "person: light skin tone, white hair",
  "🧑🏽‍🦲": "person: medium skin tone, bald",
  "🧑🏽‍🦱": "person: medium skin tone, curly hair",
  "🧑🏽‍🦰": "person: medium skin tone, red hair",
  "🧑🏽‍🦳": "person: medium skin tone, white hair",
  "🧑🏾‍🦲": "person: medium-dark skin tone, bald",
  "🧑🏾‍🦱": "person: medium-dark skin tone, curly hair",
  "🧑🏾‍🦰": "person: medium-dark skin tone, red hair",
  "🧑🏾‍🦳": "person: medium-dark skin tone, white hair",
  "🧑🏼‍🦲": "person: medium-light skin tone, bald",
  "🧑🏼‍🦱": "person: medium-light skin tone, curly hair",
  "🧑🏼‍🦰": "person: medium-light skin tone, red hair",
  "🧑🏼‍🦳": "person: medium-light skin tone, white hair",
  "🧑‍🦰": "person: red hair",
  "🧑‍🦳": "person: white hair",
  "🐦‍🔥": "phoenix",
  "🧑‍✈️": "pilot",
  "🧑🏿‍✈️": "pilot: dark skin tone",
  "🧑🏻‍✈️": "pilot: light skin tone",
  "🧑🏽‍✈️": "pilot: medium skin tone",
  "🧑🏾‍✈️": "pilot: medium-dark skin tone",
  "🧑🏼‍✈️": "pilot: medium-light skin tone",
  "🏴‍☠️": "pirate flag",
  "🐻‍❄️": "polar bear",
  "🏳️‍🌈": "rainbow flag",
  "🧑‍🔬": "scientist",
  "🧑🏿‍🔬": "scientist: dark skin tone",
  "🧑🏻‍🔬": "scientist: light skin tone",
  "🧑🏽‍🔬": "scientist: medium skin tone",
  "🧑🏾‍🔬": "scientist: medium-dark skin tone",
  "🧑🏼‍🔬": "scientist: medium-light skin tone",
  "🐕‍🦺": "service dog",
  "🧑‍🎤": "singer",
  "🧑🏿‍🎤": "singer: dark skin tone",
  "🧑🏻‍🎤": "singer: light skin tone",
  "🧑🏽‍🎤": "singer: medium skin tone",
  "🧑🏾‍🎤": "singer: medium-dark skin tone",
  "🧑🏼‍🎤": "singer: medium-light skin tone",
  "🧑‍🎓": "student",
  "🧑🏿‍🎓": "student: dark skin tone",
  "🧑🏻‍🎓": "student: light skin tone",
  "🧑🏽‍🎓": "student: medium skin tone",
  "🧑🏾‍🎓": "student: medium-dark skin tone",
  "🧑🏼‍🎓": "student: medium-light skin tone",
  "🧑‍🏫": "teacher",
  "🧑🏿‍🏫": "teacher: dark skin tone",
  "🧑🏻‍🏫": "teacher: light skin tone",
  "🧑🏽‍🏫": "teacher: medium skin tone",
  "🧑🏾‍🏫": "teacher: medium-dark skin tone",
  "🧑🏼‍🏫": "teacher: medium-light skin tone",
  "🧑‍💻": "technologist",
  "🧑🏿‍💻": "technologist: dark skin tone",
  "🧑🏻‍💻": "technologist: light skin tone",
  "🧑🏽‍💻": "technologist: medium skin tone",
  "🧑🏾‍💻": "technologist: medium-dark skin tone",
  "🧑🏼‍💻": "technologist: medium-light skin tone",
  "🏳️‍⚧️": "transgender flag",
  "👩🏿‍🤝‍👨🏻": "woman and man holding hands: dark skin tone, light skin tone",
  "👩🏿‍🤝‍👨🏽": "woman and man holding hands: dark skin tone, medium skin tone",
  "👩🏿‍🤝‍👨🏾": "woman and man holding hands: dark skin tone, medium-dark skin tone",
  "👩🏿‍🤝‍👨🏼": "woman and man holding hands: dark skin tone, medium-light skin tone",
  "👩🏻‍🤝‍👨🏿": "woman and man holding hands: light skin tone, dark skin tone",
  "👩🏻‍🤝‍👨🏽": "woman and man holding hands: light skin tone, medium skin tone",
  "👩🏻‍🤝‍👨🏾": "woman and man holding hands: light skin tone, medium-dark skin tone",
  "👩🏻‍🤝‍👨🏼": "woman and man holding hands: light skin tone, medium-light skin tone",
  "👩🏽‍🤝‍👨🏿": "woman and man holding hands: medium skin tone, dark skin tone",
  "👩🏽‍🤝‍👨🏻": "woman and man holding hands: medium skin tone, light skin tone",
  "👩🏽‍🤝‍👨🏾": "woman and man holding hands: medium skin tone, medium-dark skin tone",
  "👩🏽‍🤝‍👨🏼": "woman and man holding hands: medium skin tone, medium-light skin tone",
  "👩🏾‍🤝‍👨🏿": "woman and man holding hands: medium-dark skin tone, dark skin tone",
  "👩🏾‍🤝‍👨🏻": "woman and man holding hands: medium-dark skin tone, light skin tone",
  "👩🏾‍🤝‍👨🏽": "woman and man holding hands: medium-dark skin tone, medium skin tone",
  "👩🏾‍🤝‍👨🏼": "woman and man holding hands: medium-dark skin tone, medium-light skin tone",
  "👩🏼‍🤝‍👨🏿": "woman and man holding hands: medium-light skin tone, dark skin tone",
  "👩🏼‍🤝‍👨🏻": "woman and man holding hands: medium-light skin tone, light skin tone",
  "👩🏼‍🤝‍👨🏽": "woman and man holding hands: medium-light skin tone, medium skin tone",
  "👩🏼‍🤝‍👨🏾": "woman and man holding hands: medium-light skin tone, medium-dark skin tone",
  "👩‍🎨": "woman artist",
  "👩🏿‍🎨": "woman artist: dark skin tone",
  "👩🏻‍🎨": "woman artist: light skin tone",
  "👩🏽‍🎨": "woman artist: medium skin tone",
  "👩🏾‍🎨": "woman artist: medium-dark skin tone",
  "👩🏼‍🎨": "woman artist: medium-light skin tone",
  "👩‍🚀": "woman astronaut",
  "👩🏿‍🚀": "woman astronaut: dark skin tone",
  "👩🏻‍🚀": "woman astronaut: light skin tone",
  "👩🏽‍🚀": "woman astronaut: medium skin tone",
  "👩🏾‍🚀": "woman astronaut: medium-dark skin tone",
  "👩🏼‍🚀": "woman astronaut: medium-light skin tone",
  "🚴‍♀️": "woman biking",
  "🚴🏿‍♀️": "woman biking: dark skin tone",
  "🚴🏻‍♀️": "woman biking: light skin tone",
  "🚴🏽‍♀️": "woman biking: medium skin tone",
  "🚴🏾‍♀️": "woman biking: medium-dark skin tone",
  "🚴🏼‍♀️": "woman biking: medium-light skin tone",
  "⛹️‍♀️": "woman bouncing ball",
  "⛹🏿‍♀️": "woman bouncing ball: dark skin tone",
  "⛹🏻‍♀️": "woman bouncing ball: light skin tone",
  "⛹🏽‍♀️": "woman bouncing ball: medium skin tone",
  "⛹🏾‍♀️": "woman bouncing ball: medium-dark skin tone",
  "⛹🏼‍♀️": "woman bouncing ball: medium-light skin tone",
  "🙇‍♀️": "woman bowing",
  "🙇🏿‍♀️": "woman bowing: dark skin tone",
  "🙇🏻‍♀️": "woman bowing: light skin tone",
  "🙇🏽‍♀️": "woman bowing: medium skin tone",
  "🙇🏾‍♀️": "woman bowing: medium-dark skin tone",
  "🙇🏼‍♀️": "woman bowing: medium-light skin tone",
  "🤸‍♀️": "woman cartwheeling",
  "🤸🏿‍♀️": "woman cartwheeling: dark skin tone",
  "🤸🏻‍♀️": "woman cartwheeling: light skin tone",
  "🤸🏽‍♀️": "woman cartwheeling: medium skin tone",
  "🤸🏾‍♀️": "woman cartwheeling: medium-dark skin tone",
  "🤸🏼‍♀️": "woman cartwheeling: medium-light skin tone",
  "🧗‍♀️": "woman climbing",
  "🧗🏿‍♀️": "woman climbing: dark skin tone",
  "🧗🏻‍♀️": "woman climbing: light skin tone",
  "🧗🏽‍♀️": "woman climbing: medium skin tone",
  "🧗🏾‍♀️": "woman climbing: medium-dark skin tone",
  "🧗🏼‍♀️": "woman climbing: medium-light skin tone",
  "👷‍♀️": "woman construction worker",
  "👷🏿‍♀️": "woman construction worker: dark skin tone",
  "👷🏻‍♀️": "woman construction worker: light skin tone",
  "👷🏽‍♀️": "woman construction worker: medium skin tone",
  "👷🏾‍♀️": "woman construction worker: medium-dark skin tone",
  "👷🏼‍♀️": "woman construction worker: medium-light skin tone",
  "👩‍🍳": "woman cook",
  "👩🏿‍🍳": "woman cook: dark skin tone",
  "👩🏻‍🍳": "woman cook: light skin tone",
  "👩🏽‍🍳": "woman cook: medium skin tone",
  "👩🏾‍🍳": "woman cook: medium-dark skin tone",
  "👩🏼‍🍳": "woman cook: medium-light skin tone",
  "🕵️‍♀️": "woman detective",
  "🕵🏿‍♀️": "woman detective: dark skin tone",
  "🕵🏻‍♀️": "woman detective: light skin tone",
  "🕵🏽‍♀️": "woman detective: medium skin tone",
  "🕵🏾‍♀️": "woman detective: medium-dark skin tone",
  "🕵🏼‍♀️": "woman detective: medium-light skin tone",
  "🧝‍♀️": "woman elf",
  "🧝🏿‍♀️": "woman elf: dark skin tone",
  "🧝🏻‍♀️": "woman elf: light skin tone",
  "🧝🏽‍♀️": "woman elf: medium skin tone",
  "🧝🏾‍♀️": "woman elf: medium-dark skin tone",
  "🧝🏼‍♀️": "woman elf: medium-light skin tone",
  "🤦‍♀️": "woman facepalming",
  "🤦🏿‍♀️": "woman facepalming: dark skin tone",
  "🤦🏻‍♀️": "woman facepalming: light skin tone",
  "🤦🏽‍♀️": "woman facepalming: medium skin tone",
  "🤦🏾‍♀️": "woman facepalming: medium-dark skin tone",
  "🤦🏼‍♀️": "woman facepalming: medium-light skin tone",
  "👩‍🏭": "woman factory worker",
  "👩🏿‍🏭": "woman factory worker: dark skin tone",
  "👩🏻‍🏭": "woman factory worker: light skin tone",
  "👩🏽‍🏭": "woman factory worker: medium skin tone",
  "👩🏾‍🏭": "woman factory worker: medium-dark skin tone",
  "👩🏼‍🏭": "woman factory worker: medium-light skin tone",
  "🧚‍♀️": "woman fairy",
  "🧚🏿‍♀️": "woman fairy: dark skin tone",
  "🧚🏻‍♀️": "woman fairy: light skin tone",
  "🧚🏽‍♀️": "woman fairy: medium skin tone",
  "🧚🏾‍♀️": "woman fairy: medium-dark skin tone",
  "🧚🏼‍♀️": "woman fairy: medium-light skin tone",
  "👩‍🌾": "woman farmer",
  "👩🏿‍🌾": "woman farmer: dark skin tone",
  "👩🏻‍🌾": "woman farmer: light skin tone",
  "👩🏽‍🌾": "woman farmer: medium skin tone",
  "👩🏾‍🌾": "woman farmer: medium-dark skin tone",
  "👩🏼‍🌾": "woman farmer: medium-light skin tone",
  "👩‍🍼": "woman feeding baby",
  "👩🏿‍🍼": "woman feeding baby: dark skin tone",
  "👩🏻‍🍼": "woman feeding baby: light skin tone",
  "👩🏽‍🍼": "woman feeding baby: medium skin tone",
  "👩🏾‍🍼": "woman feeding baby: medium-dark skin tone",
  "👩🏼‍🍼": "woman feeding baby: medium-light skin tone",
  "👩‍🚒": "woman firefighter",
  "👩🏿‍🚒": "woman firefighter: dark skin tone",
  "👩🏻‍🚒": "woman firefighter: light skin tone",
  "👩🏽‍🚒": "woman firefighter: medium skin tone",
  "👩🏾‍🚒": "woman firefighter: medium-dark skin tone",
  "👩🏼‍🚒": "woman firefighter: medium-light skin tone",
  "🙍‍♀️": "woman frowning",
  "🙍🏿‍♀️": "woman frowning: dark skin tone",
  "🙍🏻‍♀️": "woman frowning: light skin tone",
  "🙍🏽‍♀️": "woman frowning: medium skin tone",
  "🙍🏾‍♀️": "woman frowning: medium-dark skin tone",
  "🙍🏼‍♀️": "woman frowning: medium-light skin tone",
  "🧞‍♀️": "woman genie",
  "🙅‍♀️": "woman gesturing NO",
  "🙅🏿‍♀️": "woman gesturing NO: dark skin tone",
  "🙅🏻‍♀️": "woman gesturing NO: light skin tone",
  "🙅🏽‍♀️": "woman gesturing NO: medium skin tone",
  "🙅🏾‍♀️": "woman gesturing NO: medium-dark skin tone",
  "🙅🏼‍♀️": "woman gesturing NO: medium-light skin tone",
  "🙆‍♀️": "woman gesturing OK",
  "🙆🏿‍♀️": "woman gesturing OK: dark skin tone",
  "🙆🏻‍♀️": "woman gesturing OK: light skin tone",
  "🙆🏽‍♀️": "woman gesturing OK: medium skin tone",
  "🙆🏾‍♀️": "woman gesturing OK: medium-dark skin tone",
  "🙆🏼‍♀️": "woman gesturing OK: medium-light skin tone",
  "💇‍♀️": "woman getting haircut",
  "💇🏿‍♀️": "woman getting haircut: dark skin tone",
  "💇🏻‍♀️": "woman getting haircut: light skin tone",
  "💇🏽‍♀️": "woman getting haircut: medium skin tone",
  "💇🏾‍♀️": "woman getting haircut: medium-dark skin tone",
  "💇🏼‍♀️": "woman getting haircut: medium-light skin tone",
  "💆‍♀️": "woman getting massage",
  "💆🏿‍♀️": "woman getting massage: dark skin tone",
  "💆🏻‍♀️": "woman getting massage: light skin tone",
  "💆🏽‍♀️": "woman getting massage: medium skin tone",
  "💆🏾‍♀️": "woman getting massage: medium-dark skin tone",
  "💆🏼‍♀️": "woman getting massage: medium-light skin tone",
  "🏌️‍♀️": "woman golfing",
  "🏌🏿‍♀️": "woman golfing: dark skin tone",
  "🏌🏻‍♀️": "woman golfing: light skin tone",
  "🏌🏽‍♀️": "woman golfing: medium skin tone",
  "🏌🏾‍♀️": "woman golfing: medium-dark skin tone",
  "🏌🏼‍♀️": "woman golfing: medium-light skin tone",
  "💂‍♀️": "woman guard",
  "💂🏿‍♀️": "woman guard: dark skin tone",
  "💂🏻‍♀️": "woman guard: light skin tone",
  "💂🏽‍♀️": "woman guard: medium skin tone",
  "💂🏾‍♀️": "woman guard: medium-dark skin tone",
  "💂🏼‍♀️": "woman guard: medium-light skin tone",
  "👩‍⚕️": "woman health worker",
  "👩🏿‍⚕️": "woman health worker: dark skin tone",
  "👩🏻‍⚕️": "woman health worker: light skin tone",
  "👩🏽‍⚕️": "woman health worker: medium skin tone",
  "👩🏾‍⚕️": "woman health worker: medium-dark skin tone",
  "👩🏼‍⚕️": "woman health worker: medium-light skin tone",
  "🧘‍♀️": "woman in lotus position",
  "🧘🏿‍♀️": "woman in lotus position: dark skin tone",
  "🧘🏻‍♀️": "woman in lotus position: light skin tone",
  "🧘🏽‍♀️": "woman in lotus position: medium skin tone",
  "🧘🏾‍♀️": "woman in lotus position: medium-dark skin tone",
  "🧘🏼‍♀️": "woman in lotus position: medium-light skin tone",
  "👩‍🦽": "woman in manual wheelchair",
  "👩‍🦽‍➡️": "woman in manual wheelchair facing right",
  "👩🏿‍🦽‍➡️": "woman in manual wheelchair facing right: dark skin tone",
  "👩🏻‍🦽‍➡️": "woman in manual wheelchair facing right: light skin tone",
  "👩🏽‍🦽‍➡️": "woman in manual wheelchair facing right: medium skin tone",
  "👩🏾‍🦽‍➡️": "woman in manual wheelchair facing right: medium-dark skin tone",
  "👩🏼‍🦽‍➡️": "woman in manual wheelchair facing right: medium-light skin tone",
  "👩🏿‍🦽": "woman in manual wheelchair: dark skin tone",
  "👩🏻‍🦽": "woman in manual wheelchair: light skin tone",
  "👩🏽‍🦽": "woman in manual wheelchair: medium skin tone",
  "👩🏾‍🦽": "woman in manual wheelchair: medium-dark skin tone",
  "👩🏼‍🦽": "woman in manual wheelchair: medium-light skin tone",
  "👩‍🦼": "woman in motorized wheelchair",
  "👩‍🦼‍➡️": "woman in motorized wheelchair facing right",
  "👩🏿‍🦼‍➡️": "woman in motorized wheelchair facing right: dark skin tone",
  "👩🏻‍🦼‍➡️": "woman in motorized wheelchair facing right: light skin tone",
  "👩🏽‍🦼‍➡️": "woman in motorized wheelchair facing right: medium skin tone",
  "👩🏾‍🦼‍➡️": "woman in motorized wheelchair facing right: medium-dark skin tone",
  "👩🏼‍🦼‍➡️": "woman in motorized wheelchair facing right: medium-light skin tone",
  "👩🏿‍🦼": "woman in motorized wheelchair: dark skin tone",
  "👩🏻‍🦼": "woman in motorized wheelchair: light skin tone",
  "👩🏽‍🦼": "woman in motorized wheelchair: medium skin tone",
  "👩🏾‍🦼": "woman in motorized wheelchair: medium-dark skin tone",
  "👩🏼‍🦼": "woman in motorized wheelchair: medium-light skin tone",
  "🧖‍♀️": "woman in steamy room",
  "🧖🏿‍♀️": "woman in steamy room: dark skin tone",
  "🧖🏻‍♀️": "woman in steamy room: light skin tone",
  "🧖🏽‍♀️": "woman in steamy room: medium skin tone",
  "🧖🏾‍♀️": "woman in steamy room: medium-dark skin tone",
  "🧖🏼‍♀️": "woman in steamy room: medium-light skin tone",
  "🤵‍♀️": "woman in tuxedo",
  "🤵🏿‍♀️": "woman in tuxedo: dark skin tone",
  "🤵🏻‍♀️": "woman in tuxedo: light skin tone",
  "🤵🏽‍♀️": "woman in tuxedo: medium skin tone",
  "🤵🏾‍♀️": "woman in tuxedo: medium-dark skin tone",
  "🤵🏼‍♀️": "woman in tuxedo: medium-light skin tone",
  "👩‍⚖️": "woman judge",
  "👩🏿‍⚖️": "woman judge: dark skin tone",
  "👩🏻‍⚖️": "woman judge: light skin tone",
  "👩🏽‍⚖️": "woman judge: medium skin tone",
  "👩🏾‍⚖️": "woman judge: medium-dark skin tone",
  "👩🏼‍⚖️": "woman judge: medium-light skin tone",
  "🤹‍♀️": "woman juggling",
  "🤹🏿‍♀️": "woman juggling: dark skin tone",
  "🤹🏻‍♀️": "woman juggling: light skin tone",
  "🤹🏽‍♀️": "woman juggling: medium skin tone",
  "🤹🏾‍♀️": "woman juggling: medium-dark skin tone",
  "🤹🏼‍♀️": "woman juggling: medium-light skin tone",
  "🧎‍♀️": "woman kneeling",
  "🧎‍♀️‍➡️": "woman kneeling facing right",
  "🧎🏿‍♀️‍➡️": "woman kneeling facing right: dark skin tone",
  "🧎🏻‍♀️‍➡️": "woman kneeling facing right: light skin tone",
  "🧎🏽‍♀️‍➡️": "woman kneeling facing right: medium skin tone",
  "🧎🏾‍♀️‍➡️": "woman kneeling facing right: medium-dark skin tone",
  "🧎🏼‍♀️‍➡️": "woman kneeling facing right: medium-light skin tone",
  "🧎🏿‍♀️": "woman kneeling: dark skin tone",
  "🧎🏻‍♀️": "woman kneeling: light skin tone",
  "🧎🏽‍♀️": "woman kneeling: medium skin tone",
  "🧎🏾‍♀️": "woman kneeling: medium-dark skin tone",
  "🧎🏼‍♀️": "woman kneeling: medium-light skin tone",
  "🏋️‍♀️": "woman lifting weights",
  "🏋🏿‍♀️": "woman lifting weights: dark skin tone",
  "🏋🏻‍♀️": "woman lifting weights: light skin tone",
  "🏋🏽‍♀️": "woman lifting weights: medium skin tone",
  "🏋🏾‍♀️": "woman lifting weights: medium-dark skin tone",
  "🏋🏼‍♀️": "woman lifting weights: medium-light skin tone",
  "🧙‍♀️": "woman mage",
  "🧙🏿‍♀️": "woman mage: dark skin tone",
  "🧙🏻‍♀️": "woman mage: light skin tone",
  "🧙🏽‍♀️": "woman mage: medium skin tone",
  "🧙🏾‍♀️": "woman mage: medium-dark skin tone",
  "🧙🏼‍♀️": "woman mage: medium-light skin tone",
  "👩‍🔧": "woman mechanic",
  "👩🏿‍🔧": "woman mechanic: dark skin tone",
  "👩🏻‍🔧": "woman mechanic: light skin tone",
  "👩🏽‍🔧": "woman mechanic: medium skin tone",
  "👩🏾‍🔧": "woman mechanic: medium-dark skin tone",
  "👩🏼‍🔧": "woman mechanic: medium-light skin tone",
  "🚵‍♀️": "woman mountain biking",
  "🚵🏿‍♀️": "woman mountain biking: dark skin tone",
  "🚵🏻‍♀️": "woman mountain biking: light skin tone",
  "🚵🏽‍♀️": "woman mountain biking: medium skin tone",
  "🚵🏾‍♀️": "woman mountain biking: medium-dark skin tone",
  "🚵🏼‍♀️": "woman mountain biking: medium-light skin tone",
  "👩‍💼": "woman office worker",
  "👩🏿‍💼": "woman office worker: dark skin tone",
  "👩🏻‍💼": "woman office worker: light skin tone",
  "👩🏽‍💼": "woman office worker: medium skin tone",
  "👩🏾‍💼": "woman office worker: medium-dark skin tone",
  "👩🏼‍💼": "woman office worker: medium-light skin tone",
  "👩‍✈️": "woman pilot",
  "👩🏿‍✈️": "woman pilot: dark skin tone",
  "👩🏻‍✈️": "woman pilot: light skin tone",
  "👩🏽‍✈️": "woman pilot: medium skin tone",
  "👩🏾‍✈️": "woman pilot: medium-dark skin tone",
  "👩🏼‍✈️": "woman pilot: medium-light skin tone",
  "🤾‍♀️": "woman playing handball",
  "🤾🏿‍♀️": "woman playing handball: dark skin tone",
  "🤾🏻‍♀️": "woman playing handball: light skin tone",
  "🤾🏽‍♀️": "woman playing handball: medium skin tone",
  "🤾🏾‍♀️": "woman playing handball: medium-dark skin tone",
  "🤾🏼‍♀️": "woman playing handball: medium-light skin tone",
  "🤽‍♀️": "woman playing water polo",
  "🤽🏿‍♀️": "woman playing water polo: dark skin tone",
  "🤽🏻‍♀️": "woman playing water polo: light skin tone",
  "🤽🏽‍♀️": "woman playing water polo: medium skin tone",
  "🤽🏾‍♀️": "woman playing water polo: medium-dark skin tone",
  "🤽🏼‍♀️": "woman playing water polo: medium-light skin tone",
  "👮‍♀️": "woman police officer",
  "👮🏿‍♀️": "woman police officer: dark skin tone",
  "👮🏻‍♀️": "woman police officer: light skin tone",
  "👮🏽‍♀️": "woman police officer: medium skin tone",
  "👮🏾‍♀️": "woman police officer: medium-dark skin tone",
  "👮🏼‍♀️": "woman police officer: medium-light skin tone",
  "🙎‍♀️": "woman pouting",
  "🙎🏿‍♀️": "woman pouting: dark skin tone",
  "🙎🏻‍♀️": "woman pouting: light skin tone",
  "🙎🏽‍♀️": "woman pouting: medium skin tone",
  "🙎🏾‍♀️": "woman pouting: medium-dark skin tone",
  "🙎🏼‍♀️": "woman pouting: medium-light skin tone",
  "🙋‍♀️": "woman raising hand",
  "🙋🏿‍♀️": "woman raising hand: dark skin tone",
  "🙋🏻‍♀️": "woman raising hand: light skin tone",
  "🙋🏽‍♀️": "woman raising hand: medium skin tone",
  "🙋🏾‍♀️": "woman raising hand: medium-dark skin tone",
  "🙋🏼‍♀️": "woman raising hand: medium-light skin tone",
  "🚣‍♀️": "woman rowing boat",
  "🚣🏿‍♀️": "woman rowing boat: dark skin tone",
  "🚣🏻‍♀️": "woman rowing boat: light skin tone",
  "🚣🏽‍♀️": "woman rowing boat: medium skin tone",
  "🚣🏾‍♀️": "woman rowing boat: medium-dark skin tone",
  "🚣🏼‍♀️": "woman rowing boat: medium-light skin tone",
  "🏃‍♀️": "woman running",
  "🏃‍♀️‍➡️": "woman running facing right",
  "🏃🏿‍♀️‍➡️": "woman running facing right: dark skin tone",
  "🏃🏻‍♀️‍➡️": "woman running facing right: light skin tone",
  "🏃🏽‍♀️‍➡️": "woman running facing right: medium skin tone",
  "🏃🏾‍♀️‍➡️": "woman running facing right: medium-dark skin tone",
  "🏃🏼‍♀️‍➡️": "woman running facing right: medium-light skin tone",
  "🏃🏿‍♀️": "woman running: dark skin tone",
  "🏃🏻‍♀️": "woman running: light skin tone",
  "🏃🏽‍♀️": "woman running: medium skin tone",
  "🏃🏾‍♀️": "woman running: medium-dark skin tone",
  "🏃🏼‍♀️": "woman running: medium-light skin tone",
  "👩‍🔬": "woman scientist",
  "👩🏿‍🔬": "woman scientist: dark skin tone",
  "👩🏻‍🔬": "woman scientist: light skin tone",
  "👩🏽‍🔬": "woman scientist: medium skin tone",
  "👩🏾‍🔬": "woman scientist: medium-dark skin tone",
  "👩🏼‍🔬": "woman scientist: medium-light skin tone",
  "🤷‍♀️": "woman shrugging",
  "🤷🏿‍♀️": "woman shrugging: dark skin tone",
  "🤷🏻‍♀️": "woman shrugging: light skin tone",
  "🤷🏽‍♀️": "woman shrugging: medium skin tone",
  "🤷🏾‍♀️": "woman shrugging: medium-dark skin tone",
  "🤷🏼‍♀️": "woman shrugging: medium-light skin tone",
  "👩‍🎤": "woman singer",
  "👩🏿‍🎤": "woman singer: dark skin tone",
  "👩🏻‍🎤": "woman singer: light skin tone",
  "👩🏽‍🎤": "woman singer: medium skin tone",
  "👩🏾‍🎤": "woman singer: medium-dark skin tone",
  "👩🏼‍🎤": "woman singer: medium-light skin tone",
  "🧍‍♀️": "woman standing",
  "🧍🏿‍♀️": "woman standing: dark skin tone",
  "🧍🏻‍♀️": "woman standing: light skin tone",
  "🧍🏽‍♀️": "woman standing: medium skin tone",
  "🧍🏾‍♀️": "woman standing: medium-dark skin tone",
  "🧍🏼‍♀️": "woman standing: medium-light skin tone",
  "👩‍🎓": "woman student",
  "👩🏿‍🎓": "woman student: dark skin tone",
  "👩🏻‍🎓": "woman student: light skin tone",
  "👩🏽‍🎓": "woman student: medium skin tone",
  "👩🏾‍🎓": "woman student: medium-dark skin tone",
  "👩🏼‍🎓": "woman student: medium-light skin tone",
  "🦸‍♀️": "woman superhero",
  "🦸🏿‍♀️": "woman superhero: dark skin tone",
  "🦸🏻‍♀️": "woman superhero: light skin tone",
  "🦸🏽‍♀️": "woman superhero: medium skin tone",
  "🦸🏾‍♀️": "woman superhero: medium-dark skin tone",
  "🦸🏼‍♀️": "woman superhero: medium-light skin tone",
  "🦹‍♀️": "woman supervillain",
  "🦹🏿‍♀️": "woman supervillain: dark skin tone",
  "🦹🏻‍♀️": "woman supervillain: light skin tone",
  "🦹🏽‍♀️": "woman supervillain: medium skin tone",
  "🦹🏾‍♀️": "woman supervillain: medium-dark skin tone",
  "🦹🏼‍♀️": "woman supervillain: medium-light skin tone",
  "🏄‍♀️": "woman surfing",
  "🏄🏿‍♀️": "woman surfing: dark skin tone",
  "🏄🏻‍♀️": "woman surfing: light skin tone",
  "🏄🏽‍♀️": "woman surfing: medium skin tone",
  "🏄🏾‍♀️": "woman surfing: medium-dark skin tone",
  "🏄🏼‍♀️": "woman surfing: medium-light skin tone",
  "🏊‍♀️": "woman swimming",
  "🏊🏿‍♀️": "woman swimming: dark skin tone",
  "🏊🏻‍♀️": "woman swimming: light skin tone",
  "🏊🏽‍♀️": "woman swimming: medium skin tone",
  "🏊🏾‍♀️": "woman swimming: medium-dark skin tone",
  "🏊🏼‍♀️": "woman swimming: medium-light skin tone",
  "👩‍🏫": "woman teacher",
  "👩🏿‍🏫": "woman teacher: dark skin tone",
  "👩🏻‍🏫": "woman teacher: light skin tone",
  "👩🏽‍🏫": "woman teacher: medium skin tone",
  "👩🏾‍🏫": "woman teacher: medium-dark skin tone",
  "👩🏼‍🏫": "woman teacher: medium-light skin tone",
  "👩‍💻": "woman technologist",
  "👩🏿‍💻": "woman technologist: dark skin tone",
  "👩🏻‍💻": "woman technologist: light skin tone",
  "👩🏽‍💻": "woman technologist: medium skin tone",
  "👩🏾‍💻": "woman technologist: medium-dark skin tone",
  "👩🏼‍💻": "woman technologist: medium-light skin tone",
  "💁‍♀️": "woman tipping hand",
  "💁🏿‍♀️": "woman tipping hand: dark skin tone",
  "💁🏻‍♀️": "woman tipping hand: light skin tone",
  "💁🏽‍♀️": "woman tipping hand: medium skin tone",
  "💁🏾‍♀️": "woman tipping hand: medium-dark skin tone",
  "💁🏼‍♀️": "woman tipping hand: medium-light skin tone",
  "🧛‍♀️": "woman vampire",
  "🧛🏿‍♀️": "woman vampire: dark skin tone",
  "🧛🏻‍♀️": "woman vampire: light skin tone",
  "🧛🏽‍♀️": "woman vampire: medium skin tone",
  "🧛🏾‍♀️": "woman vampire: medium-dark skin tone",
  "🧛🏼‍♀️": "woman vampire: medium-light skin tone",
  "🚶‍♀️": "woman walking",
  "🚶‍♀️‍➡️": "woman walking facing right",
  "🚶🏿‍♀️‍➡️": "woman walking facing right: dark skin tone",
  "🚶🏻‍♀️‍➡️": "woman walking facing right: light skin tone",
  "🚶🏽‍♀️‍➡️": "woman walking facing right: medium skin tone",
  "🚶🏾‍♀️‍➡️": "woman walking facing right: medium-dark skin tone",
  "🚶🏼‍♀️‍➡️": "woman walking facing right: medium-light skin tone",
  "🚶🏿‍♀️": "woman walking: dark skin tone",
  "🚶🏻‍♀️": "woman walking: light skin tone",
  "🚶🏽‍♀️": "woman walking: medium skin tone",
  "🚶🏾‍♀️": "woman walking: medium-dark skin tone",
  "🚶🏼‍♀️": "woman walking: medium-light skin tone",
  "👳‍♀️": "woman wearing turban",
  "👳🏿‍♀️": "woman wearing turban: dark skin tone",
  "👳🏻‍♀️": "woman wearing turban: light skin tone",
  "👳🏽‍♀️": "woman wearing turban: medium skin tone",
  "👳🏾‍♀️": "woman wearing turban: medium-dark skin tone",
  "👳🏼‍♀️": "woman wearing turban: medium-light skin tone",
  "👰‍♀️": "woman with veil",
  "👰🏿‍♀️": "woman with veil: dark skin tone",
  "👰🏻‍♀️": "woman with veil: light skin tone",
  "👰🏽‍♀️": "woman with veil: medium skin tone",
  "👰🏾‍♀️": "woman with veil: medium-dark skin tone",
  "👰🏼‍♀️": "woman with veil: medium-light skin tone",
  "👩‍🦯": "woman with white cane",
  "👩‍🦯‍➡️": "woman with white cane facing right",
  "👩🏿‍🦯‍➡️": "woman with white cane facing right: dark skin tone",
  "👩🏻‍🦯‍➡️": "woman with white cane facing right: light skin tone",
  "👩🏽‍🦯‍➡️": "woman with white cane facing right: medium skin tone",
  "👩🏾‍🦯‍➡️": "woman with white cane facing right: medium-dark skin tone",
  "👩🏼‍🦯‍➡️": "woman with white cane facing right: medium-light skin tone",
  "👩🏿‍🦯": "woman with white cane: dark skin tone",
  "👩🏻‍🦯": "woman with white cane: light skin tone",
  "👩🏽‍🦯": "woman with white cane: medium skin tone",
  "👩🏾‍🦯": "woman with white cane: medium-dark skin tone",
  "👩🏼‍🦯": "woman with white cane: medium-light skin tone",
  "🧟‍♀️": "woman zombie",
  "👩‍🦲": "woman: bald",
  "🧔‍♀️": "woman: beard",
  "👱‍♀️": "woman: blond hair",
  "👩‍🦱": "woman: curly hair",
  "👩🏿‍🦲": "woman: dark skin tone, bald",
  "🧔🏿‍♀️": "woman: dark skin tone, beard",
  "👱🏿‍♀️": "woman: dark skin tone, blond hair",
  "👩🏿‍🦱": "woman: dark skin tone, curly hair",
  "👩🏿‍🦰": "woman: dark skin tone, red hair",
  "👩🏿‍🦳": "woman: dark skin tone, white hair",
  "👩🏻‍🦲": "woman: light skin tone, bald",
  "🧔🏻‍♀️": "woman: light skin tone, beard",
  "👱🏻‍♀️": "woman: light skin tone, blond hair",
  "👩🏻‍🦱": "woman: light skin tone, curly hair",
  "👩🏻‍🦰": "woman: light skin tone, red hair",
  "👩🏻‍🦳": "woman: light skin tone, white hair",
  "👩🏽‍🦲": "woman: medium skin tone, bald",
  "🧔🏽‍♀️": "woman: medium skin tone, beard",
  "👱🏽‍♀️": "woman: medium skin tone, blond hair",
  "👩🏽‍🦱": "woman: medium skin tone, curly hair",
  "👩🏽‍🦰": "woman: medium skin tone, red hair",
  "👩🏽‍🦳": "woman: medium skin tone, white hair",
  "👩🏾‍🦲": "woman: medium-dark skin tone, bald",
  "🧔🏾‍♀️": "woman: medium-dark skin tone, beard",
  "👱🏾‍♀️": "woman: medium-dark skin tone, blond hair",
  "👩🏾‍🦱": "woman: medium-dark skin tone, curly hair",
  "👩🏾‍🦰": "woman: medium-dark skin tone, red hair",
  "👩🏾‍🦳": "woman: medium-dark skin tone, white hair",
  "👩🏼‍🦲": "woman: medium-light skin tone, bald",
  "🧔🏼‍♀️": "woman: medium-light skin tone, beard",
  "👱🏼‍♀️": "woman: medium-light skin tone, blond hair",
  "👩🏼‍🦱": "woman: medium-light skin tone, curly hair",
  "👩🏼‍🦰": "woman: medium-light skin tone, red hair",
  "👩🏼‍🦳": "woman: medium-light skin tone, white hair",
  "👩‍🦰": "woman: red hair",
  "👩‍🦳": "woman: white hair",
  "👯‍♀️": "women with bunny ears",
  "🤼‍♀️": "women wrestling",
} as const;
