---
description: 'Ensure consistent indexer versions across various contexts'
name: 'Indexer versions'
runs:
  steps:
  - id: 'say-hello'
    run: 'sh ${{ github.action_path }}/sh/print.sh'
    shell: 'sh'
  using: 'composite'
...
