---
description: 'Ensure consistent indexer versions across various contexts'
name: 'Indexer versions'
runs:
  steps:
  - id: 'check-deploy-files'
    run: 'sh ${{ github.action_path }}/sh/check-deploy-files.sh'
    shell: 'sh'
  - id: 'check-compose-file'
    run: 'sh ${{ github.action_path }}/sh/check-compose-file.sh'
    shell: 'sh'
  using: 'composite'
...
