---
description: 'Ensure consistent indexer versions across various contexts'
name: 'Indexer versions'
runs:
  steps:
  - env:
      DEPLOY_FILE_SUFFIX: 'production'
    id: 'get-production-versions'
    run: 'sh ${{ github.action_path }}/sh/get-deploy-file-versions.sh'
    shell: 'sh'
  using: 'composite'
...
