[package]
name = "sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
aptos-protos.workspace = true
bigdecimal.workspace = true
finl_unicode = "1.3.0"
serde.workspace = true
serde_json.workspace = true
