---
name: "pnpm install"
description: "Installs node.js, pnpm, then runs pnpm install."
runs:
  steps:
  - name: 'Install pnpm'
    uses: 'pnpm/action-setup@v4'
    with:
      package_json_file: 'src/typescript/package.json'
  - name: 'Install node.js'
    uses: 'actions/setup-node@v4'
    with:
      cache: 'pnpm'
      cache-dependency-path: 'src/typescript/pnpm-lock.yaml'
      node-version-file: 'src/typescript/.node-version'
  - name: 'Install dependencies'
    run: 'pnpm install'
  using: "composite"
...
