[addresses]
black_cat_market = "0x57db9cd8ed6aefbb302d465143367c6f72f0d9f4c5c35fa54eab62655dd8e9f4"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "BlackCatCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
