[addresses]
incentives = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
coin_factory = "0xaaaa"
emojicoin_dot_fun = "0xc0de"
incentives = "0xbbbb"

[dev-dependencies.EmojicoinDotFun]
local = "../emojicoin_dot_fun"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "Incentives"
upgrade_policy = "compatible"
version = "1.0.0"
