[addresses]
emojicoin_dot_fun="0xc87af7d6288ea04fa4fbc840bb92419f957e8e92e2d4ab4cc8e55866b6974d35"
admin="0x296e53ce1956ebdef5d969f3189a00b0ca29f2d377b311e30872202d4072b19b"
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
coin_factory = "0xa8a56419ed5290392257642429bfe4fc7f6c6b6c95cbbb2b13c22db1d70afc8c"


[dev-dependencies.BlackCatCoinFactory]
local = "../test_coin_factories/black_cat"

[dev-dependencies.BlackHeartCoinFactory]
local = "../test_coin_factories/black_heart"

[dev-dependencies.EmojicoinDotFunCoinFactory]
local = "../coin_factory"

[dev-dependencies.YellowHeartCoinFactory]
local = "../test_coin_factories/yellow_heart"



[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "EmojicoinDotFun"
upgrade_policy = "immutable"
version = "1.0.1"
