[addresses]
yellow_heart_market = "0xc050f3cc6b85ef42a2fb3ab073f6343c32b19c3c25f876c8ab3eb2c07aca1972"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "YellowHeartCoinFactory"
upgrade_policy = "compatible"
version = "1.0.0"
