[addresses]
yellow_heart_market = "0xb28d1650af0b7b2739d975c58d96bc2f4dd9a4c70aed6bdc94e5f49a3499ee01"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "YellowHeartCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
