# cspell:word TMPDIR
---
name: |
  Run the TypeScript formatter
runs:
  steps:
  - uses: 'actions/setup-node@v3'
    with:
      node-version-file: 'src/typescript/.node-version'
      registry-url: 'https://registry.npmjs.org'
  - uses: 'pnpm/action-setup@v2'
    with:
      version: '8.9.0'
  - run: |
      cd src/typescript && pnpm install --frozen-lockfile && pnpm _fmt --check
    shell: 'bash'
  using: 'composite'
...
