---
Mappings:
  # Use one map entry for constants to prevent them from being overloaded,
  # which would be possible if they were parameters.
  Constants:
    Defaults:
      VpcCidrBlock: '10.0.0.0/16'
Resources:
  # Virtual private cloud for internal networking.
  Vpc:
    Properties:
      CidrBlock: !FindInMap
      - 'Constants'
      - 'Defaults'
      - 'VpcCidrBlock'
      EnableDnsHostnames: true
      EnableDnsSupport: true
    Type: 'AWS::EC2::VPC'
Transform: 'AWS::LanguageExtensions'
...
