# Contains a minimal template, used to test stack teardown by pointing the
# stack deployment file to this template.
---
Metadata:
  cfn-lint:
    config:
      ignore_checks:
      - 'W2001'
Parameters:
  ProvisionBastionHost:
    Default: 'false'
    Type: 'String'
Resources:
  NullBucket:
    Type: 'AWS::S3::Bucket'
...
