---
jobs:
  indexer-versions:
    name: 'Indexer versions'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: './.github/actions/version-checker'
name: 'Indexer versions'
'on':
  merge_group: null
  pull_request: null
...
