---
jobs:
  indexer-versions:
    environment: 'github-actions'
    name: 'Indexer versions'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: './.github/actions/indexer-versions'
name: 'Indexer versions'
'on':
  merge_group: null
  pull_request:
    branches:
    - 'production'
    - 'fallback'
...
