---
env:
  GITHUB_ACCESS_TOKEN: '${{ secrets.TRADING_VIEW_REPO_ACCESS_TOKEN }}'
  TRADING_VIEW_REPO_OWNER: '${{ secrets.TRADING_VIEW_REPO_OWNER }}'
jobs:
  test:
    defaults:
      run:
        working-directory: 'src/typescript'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'actions/setup-node@v4'
      with:
        node-version: 'lts/*'
    - name: 'Install dependencies'
      run: 'npm install -g pnpm && pnpm install'
    - name: 'Prepare CI env'
      run: 'pnpm run playwright-preps'
    - name: 'Run pnpm i'
      run: 'pnpm i'
    - name: 'Install Playwright Browsers'
      run: 'pnpm exec playwright install --with-deps'
    - name: 'Copy env file'
      run: 'cp ci.env .env'
    - name: 'Run Playwright tests'
      run: 'pnpm exec playwright test'
    - if: 'always()'
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'playwright-report'
        path: 'playwright-report/'
        retention-days: 30
    timeout-minutes: 60
name: 'Playwright Tests'
"on":
  pull_request:
    branches:
    - 'main'
    - 'production'
  push:
    branches:
    - 'main'
    - 'production'
...
