---
jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - run: 'git submodule update --init --recursive src/rust/processor'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econialabs/emojicoin-dot-fun-indexer-processor'
        tags: |
          type=match,pattern=processor-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: 'src/rust/processor/rust'
        file: 'src/rust/processor/rust/Dockerfile'
        labels: '${{ steps.metadata.outputs.labels }}'
        platforms: 'linux/amd64'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
name: 'Build processor Docker image and push to Docker Hub'
'on':
  push:
    tags:
    - 'processor-v*'
...
