---
env:
  DOCKER_IMAGE_PLATFORM: 'linux/amd64'
  PUBLISHER_PK: >-
    0xeaa964d1353b075ac63b0c5a0c1e92aa93355be1402f6077581e37e2a846105e
  BIG_MONEY_GUY_PK: >-
    0xa5e11183d0c23b8c49b40dd71bba7fa0992aed9b89c42934a1bb8f6e4ccc4ec4
jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        submodules: 'false'
    - name: 'Install the latest Aptos CLI'
      uses: './.github/actions/get-latest-aptos-cli'
      with:
        destination_directory: '/usr/local/bin'
    - name: 'Create the Move JSON publish payloads'
      run: 'bash src/docker/emojicoin-aptos-node/sh/create-publish-payloads.sh'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econialabs/emojicoin-aptos-node'
        tags: |
          type=match,pattern=emojicoin-aptos-node-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        build-args: |
          PUBLISHER_PK=${{ env.PUBLISHER_PK }}
          BIG_MONEY_GUY_PK=${{ env.BIG_MONEY_GUY_PK }}
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: '.'
        file: 'src/docker/emojicoin-aptos-node/Dockerfile'
        labels: '${{ steps.metadata.outputs.labels }}'
        # The emojicoin-node image can only be built for the platform on which
        # the build is running. This is because the build process requires
        # running `aptos node run-localnet`, which spawns a new container. This
        # new container must be able to run the `aptos` binary, which is only
        # available for the platform on which the build is running.
        platforms: '${{ env.DOCKER_IMAGE_PLATFORM }}'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
    timeout-minutes: 360
name: |
  Build the emojicoin Aptos node Docker image and push to Docker Hub
'on':
  push:
    tags:
    - 'emojicoin-aptos-node-v*'
...
