# cspell:word localnet
---
env:
  PUBLISHER_PRIVATE_KEY: >-
    0xeaa964d1353b075ac63b0c5a0c1e92aa93355be1402f6077581e37e2a846105e
jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econialabs/emojicoin-dot-fun-localnet-publisher'
        tags: |
          type=match,pattern=emojicoin-dot-fun-localnet-publisher-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        build-args: |
          PUBLISHER_PRIVATE_KEY=${{ env.PUBLISHER_PRIVATE_KEY }}
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: '.'
        file: 'src/docker/localnet-publisher/Dockerfile'
        labels: '${{ steps.metadata.outputs.labels }}'
        platforms: '${{ vars.DOCKER_IMAGE_PLATFORMS }}'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
    timeout-minutes: 360
name: 'Build the localnet-publisher Docker image and push to Dockerhub'
'on':
  push:
    tags:
    - 'emojicoin-dot-fun-localnet-publisher*'
  workflow_dispatch: null
...
