---
jobs:
  run-tests:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - uses: './.github/actions/run-tests'
name: 'Run emojicoin dot fun TypeScript E2E and unit tests with a local testnet'
'on':
  pull_request:
    types: |
      labeled
      opened
      synchronize
      reopened
      auto_merge_enabled
  push:
    branches:
    - 'main'
...
