---
jobs:
  verify-submodule:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - run: 'git submodule update --init --recursive src/rust/processor'
    # yamllint disable rule:indentation
    - run: |
        branch="${{ github.head_ref || github.ref_name }}"
        target_branch="emojicoin-dot-fun"
        if [ "$branch" = "arena" ]; then
          target_branch="emojicoin-arena"
        fi
        git fetch origin $target_branch
        git diff --quiet origin/$target_branch
      working-directory: 'src/rust/processor'
      # yamllint enable rule:indentation
name: 'Ensure correct version of processor submodule'
'on':
  pull_request: null
  push:
    branches:
    - 'main'
  workflow_dispatch: null
...
