---
jobs:
  pre-commit:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - run: 'git submodule update --init --recursive src/rust/processor'
    - run: 'git fetch'
      working-directory: 'src/rust/processor'
    - run: 'git diff --quiet origin/emojicoin-dot-fun'
      working-directory: 'src/rust/processor'
name: 'Ensure correct version of processor submodule'
'on':
  pull_request: null
  push:
    branches:
    - 'main'
  workflow_dispatch: null
...
