---
jobs:
  ts-tests:
    defaults:
      run:
        working-directory: 'src/typescript'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        submodules: 'false'
    - uses: 'actions/setup-node@v4'
      with:
        node-version-file: 'src/typescript/.node-version'
    - name: 'Install dependencies'
      run: 'npm install -g pnpm && pnpm install'
    - name: 'Install the latest Aptos CLI'
      # yamllint disable-line rule:line-length
      uses: 'aptos-labs/aptos-core/.github/actions/get-latest-cli@8792eefecd537c33fb879984635a0762838e2329'
      with:
        destination_directory: '/usr/local/bin'
    - env:
        EMOJICOIN_ARENA_MODULE_ADDRESS: >-
          0xf000d910b99722d201c6cf88eb7d1112b43475b9765b118f289b5d65d919000d
        NEXT_PUBLIC_ARENA_MODULE_ADDRESS: >-
          0xf000d910b99722d201c6cf88eb7d1112b43475b9765b118f289b5d65d919000d
        NEXT_PUBLIC_MODULE_ADDRESS: >-
          0xf000d910b99722d201c6cf88eb7d1112b43475b9765b118f289b5d65d919000d
        PUBLISHER_PRIVATE_KEY: >-
          0xeaa964d1353b075ac63b0c5a0c1e92aa93355be1402f6077581e37e2a846105e
      name: '${{ matrix.job-name }}'
      run: '${{ matrix.command }}'
    - if: 'failure()'
      name: 'Print local testnet logs on failure'
      run: 'cat ${{ runner.temp }}/local-testnet-logs.txt'
      shell: 'bash'
    timeout-minutes: 15
    strategy:
      matrix:
        include:
        - job-name: 'FE:  [unit]'
          command: 'pnpm run test:frontend:unit'
        - job-name: 'SDK: [unit]'
          command: 'pnpm run test:sdk:unit'
        - job-name: 'SDK: [e2e, base, general]'
          command: 'pnpm run test:sdk:e2e:base-general'
        - job-name: 'SDK: [e2e, base, websockets]'
          command: 'pnpm run test:sdk:e2e:base-ws'
        - job-name: 'SDK: [e2e, arena, general]'
          command: 'pnpm run test:sdk:e2e:arena-general'
        - job-name: 'SDK: [e2e, arena, websockets]'
          command: 'pnpm run test:sdk:e2e:arena-ws'
        - job-name: 'SDK: [e2e, arena, candlesticks]'
          command: 'pnpm run test:sdk:e2e:arena-candlesticks'
name: 'Run test suite'
'on':
  merge_group: null
  pull_request: null
  push:
    branches:
    - 'main'
    - 'production'
  workflow_dispatch: null
...
