# yamllint disable rule:empty-lines
# yamllint disable rule:key-ordering
---
name: 'typescript'

'on':
  merge_group: null
  pull_request: null
  workflow_dispatch: null

defaults:
  run:
    working-directory: 'src/typescript'

jobs:
  lint:
    name: 'TS lint'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        submodules: 'false'
    - uses: './.github/actions/pnpm-install'
    - run: 'pnpm run lint'

  format:
    name: 'TS format'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        submodules: 'false'
    - uses: './.github/actions/pnpm-install'
    - run: 'pnpm run format:check'

  tsc-check:
    name: 'TS compile check'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        submodules: 'false'
    - uses: './.github/actions/pnpm-install'
    - run: 'pnpm run check'

  tests:
    name: 'test suite / (${{ matrix.pretty-suffix }})'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        submodules: 'false'
    - uses: './.github/actions/pnpm-install'
    - env:
        EMOJICOIN_ARENA_MODULE_ADDRESS: >-
          0xf000d910b99722d201c6cf88eb7d1112b43475b9765b118f289b5d65d919000d
        NEXT_PUBLIC_ARENA_MODULE_ADDRESS: >-
          0xf000d910b99722d201c6cf88eb7d1112b43475b9765b118f289b5d65d919000d
        NEXT_PUBLIC_MODULE_ADDRESS: >-
          0xf000d910b99722d201c6cf88eb7d1112b43475b9765b118f289b5d65d919000d
        PUBLISHER_PRIVATE_KEY: >-
          0xeaa964d1353b075ac63b0c5a0c1e92aa93355be1402f6077581e37e2a846105e
      run: >-
        pnpm run test:$(echo "${{ matrix.pretty-suffix }}" | sed "s/, /:/g")
    - if: 'failure()'
      name: 'Print local testnet logs on failure'
      run: 'cat ${{ runner.temp }}/local-testnet-logs.txt'
      shell: 'bash'
    strategy:
      matrix:
        include:
        - pretty-suffix: 'frontend, unit'
        - pretty-suffix: 'sdk, unit'
        - pretty-suffix: 'sdk, e2e, base-general'
        - pretty-suffix: 'sdk, e2e, base-ws'
        - pretty-suffix: 'sdk, e2e, arena-general'
        - pretty-suffix: 'sdk, e2e, arena-ws'
        - pretty-suffix: 'sdk, e2e, arena-candlesticks'
        - pretty-suffix: 'sdk, e2e, candlesticks'
    timeout-minutes: 15
...
